import type { NavigationItem } from "@/types/navigation";
import { APP_ROUTES } from "./routes";

export const NAVIGATION_ITEMS = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: APP_ROUTES.dashboard,
    description: "Ringkasan dataset, sentimen, aspek, prioritas, dan status model.",
    iconName: "LayoutDashboard",
    order: 1,
    status: "planned",
  },
  {
    id: "dataset",
    label: "Dataset",
    href: APP_ROUTES.dataset,
    description: "Memeriksa data ulasan Spotify dan ringkasan kualitas data.",
    iconName: "Database",
    order: 2,
    status: "planned",
  },
  {
    id: "scraping",
    label: "Scraping",
    href: APP_ROUTES.scraping,
    description: "Status pengumpulan ulasan dan ringkasan batch scraping.",
    iconName: "DownloadCloud",
    order: 3,
    status: "planned",
  },
  {
    id: "preprocessing",
    label: "Prapemrosesan",
    href: APP_ROUTES.preprocessing,
    description: "Pipeline pembersihan teks dan sampel ulasan sebelum-sesudah.",
    iconName: "Sparkles",
    order: 4,
    status: "planned",
  },
  {
    id: "sentiment-analysis",
    label: "Analisis Sentimen",
    href: APP_ROUTES.sentimentAnalysis,
    description: "Output sentimen IndoBERT dan ringkasan confidence.",
    iconName: "MessageSquareText",
    order: 5,
    status: "planned",
  },
  {
    id: "aspect-classification",
    label: "Klasifikasi Aspek",
    href: APP_ROUTES.aspectClassification,
    description: "Label aspek SVM dan pengelompokan ulasan negatif.",
    iconName: "Tags",
    order: 6,
    status: "planned",
  },
  {
    id: "ahp-fuzzy-ahp",
    label: "AHP / Fuzzy AHP",
    href: APP_ROUTES.ahpFuzzyAhp,
    description: "Alur prioritisasi fleksibel untuk aspek negatif ulasan Spotify.",
    iconName: "ListOrdered",
    order: 7,
    status: "planned",
  },
  {
    id: "model-evaluation",
    label: "Evaluasi Model",
    href: APP_ROUTES.modelEvaluation,
    description: "Metrik model sentimen dan aspek.",
    iconName: "Gauge",
    order: 8,
    status: "planned",
  },
  {
    id: "reports",
    label: "Laporan",
    href: APP_ROUTES.reports,
    description: "Ringkasan siap skripsi dan temuan yang siap diekspor.",
    iconName: "FileText",
    order: 9,
    status: "planned",
  },
  {
    id: "settings",
    label: "Pengaturan",
    href: APP_ROUTES.settings,
    description: "Metadata aplikasi, placeholder API, dan status sistem.",
    iconName: "Settings",
    order: 10,
    status: "planned",
  },
] as const satisfies readonly NavigationItem[];
