import type { NavigationItem } from "@/types/navigation";
import { APP_ROUTES } from "./routes";

export const NAVIGATION_ITEMS = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: APP_ROUTES.dashboard,
    description: "Ringkasan dataset, model, aspek, dan prioritas.",
    iconName: "LayoutDashboard",
    order: 1,
    status: "planned",
  },
  {
    id: "dataset",
    label: "Dataset",
    href: APP_ROUTES.dataset,
    description: "Data ulasan Spotify dan kualitas dataset.",
    iconName: "Database",
    order: 2,
    status: "planned",
  },
  {
    id: "preprocessing",
    label: "Prapemrosesan",
    href: APP_ROUTES.preprocessing,
    description: "Pembersihan teks dan pembentukan data model.",
    iconName: "Sparkles",
    order: 3,
    status: "planned",
  },
  {
    id: "sentiment-analysis",
    label: "Analisis Sentimen",
    href: APP_ROUTES.sentimentAnalysis,
    description: "Evaluasi dan hasil prediksi IndoBERT.",
    iconName: "MessageSquareText",
    order: 4,
    status: "planned",
  },
  {
    id: "aspect-classification",
    label: "Klasifikasi Aspek",
    href: APP_ROUTES.aspectClassification,
    description: "Evaluasi dan hasil prediksi SVM.",
    iconName: "Tags",
    order: 5,
    status: "planned",
  },
  {
    id: "inference",
    label: "Uji Ulasan",
    href: APP_ROUTES.inference,
    description: "Uji satu ulasan dengan IndoBERT dan SVM.",
    iconName: "ScanText",
    order: 6,
    status: "planned",
  },
  {
    id: "ahp-fuzzy-ahp",
    label: "AHP / Fuzzy AHP",
    href: APP_ROUTES.ahpFuzzyAhp,
    description: "Prioritas aspek negatif ulasan Spotify.",
    iconName: "ListOrdered",
    order: 7,
    status: "planned",
  },
] as const satisfies readonly NavigationItem[];
