# ═══════════════════════════════════════════════════════════════════════════════
#  slang_dict.py — Kamus Normalisasi Slang Bahasa Indonesia + Inggris
#  Domain  : Ulasan Aplikasi Mobile (Spotify, dll.) di Google Play Store
#  Total   : 1,986+ entri
#  Versi   : 2.0
# ═══════════════════════════════════════════════════════════════════════════════

SLANG_DICT: dict[str, str] = {
    'awkarin'                     : '',
    'di-'                         : '',
    'emm'                         : '',
    'haha'                        : '',
    'hehe'                        : '',
    'hehehe'                      : '',
    'hihi'                        : '',
    'hm'                          : '',
    'hmm'                         : '',
    'kwkwk'                       : '',
    'nge'                         : '',
    'ugh'                         : '',
    'um'                          : '',
    'wkkwk'                       : '',
    'wkwk'                        : '',
    'wkwkwk'                      : '',
    'wkwkwkwk'                    : '',
    'xDD'                         : '',
    'xd'                          : '',
    '320kbps'                     : '320kbps',
    'aac'                         : 'aac',
    'abang'                       : 'abang',
    'bang'                        : 'abang',
    'random'                      : 'acak',
    'shuffle'                     : 'acak',
    'aduh'                        : 'aduh',
    'aduhai'                      : 'aduh',
    'duh'                         : 'aduh',
    'hadeeh'                      : 'aduh',
    'hadeh'                       : 'aduh',
    'haduh'                       : 'aduh',
    'haish'                       : 'aduh',
    'haissh'                      : 'aduh',
    'waduh'                       : 'aduh',
    'agar'                        : 'agar',
    'so that'                     : 'agar',
    'airplay'                     : 'airplay',
    'akhir'                       : 'akhir',
    'akhirnya'                    : 'akhirnya',
    'finally'                     : 'akhirnya',
    'as a result'                 : 'akibatnya',
    'consequently'                : 'akibatnya',
    'access'                      : 'akses',
    'activate'                    : 'aktifkan',
    'enable'                      : 'aktifkan',
    'friend activity'             : 'aktivitas teman',
    'acc'                         : 'akun',
    'account'                     : 'akun',
    'akun'                        : 'akun',
    'akun diretas'                : 'akun diretas',
    'akun kena hack'              : 'akun diretas',
    'accurate'                    : 'akurat',
    'acoustic'                    : 'akustik',
    'album'                       : 'album',
    'algo'                        : 'algoritma',
    'algorithm'                   : 'algoritma',
    'toggle'                      : 'alihkan',
    'aliran'                      : 'aliran',
    'alpha'                       : 'alpha',
    'aman'                        : 'aman',
    'safe'                        : 'aman',
    'secure'                      : 'aman',
    'reliable'                    : 'andal',
    'android'                     : 'android',
    'aneh'                        : 'aneh',
    'strange'                     : 'aneh',
    'weird'                       : 'aneh',
    'interface'                   : 'antarmuka',
    'ui'                          : 'antarmuka',
    'que'                         : 'antrean',
    'queue'                       : 'antrean',
    'excited'                     : 'antusias',
    'apaan'                       : 'apa',
    'apadeh'                      : 'apa',
    'apasih'                      : 'apa',
    'apa2'                        : 'apa saja',
    'api'                         : 'api',
    'apk'                         : 'aplikasi',
    'apl'                         : 'aplikasi',
    'aplik'                       : 'aplikasi',
    'aplks'                       : 'aplikasi',
    'aplksi'                      : 'aplikasi',
    'app'                         : 'aplikasi',
    'application'                 : 'aplikasi',
    'apps'                        : 'aplikasi',
    'app2'                        : 'aplikasi-aplikasi',
    'apple store'                 : 'app store',
    'appstore'                    : 'app store',
    'apple music'                 : 'apple music',
    'artis'                       : 'artis',
    'artist'                      : 'artis',
    'asal'                        : 'asalkan',
    'asalkan'                     : 'asalkan',
    'provided'                    : 'asalkan',
    'astaga'                      : 'astaga',
    'astaghfirullah'              : 'astaga',
    'oh my god'                   : 'astaga',
    'omg'                         : 'astaga',
    'omgg'                        : 'astaga',
    'what the'                    : 'astaga',
    'wtf'                         : 'astaga',
    'yaallah'                     : 'astaga',
    'yaampun'                     : 'astaga',
    'atau'                        : 'atau',
    'maupun'                      : 'atau',
    'reset'                       : 'atur ulang',
    'audio'                       : 'audio',
    'audio berkualitas'           : 'audio berkualitas',
    '2fa'                         : 'autentikasi dua faktor',
    'cloud'                       : 'awan',
    'bgmn'                        : 'bagaimana',
    'gimana'                      : 'bagaimana',
    'gimana sih'                  : 'bagaimana',
    'gimana ya'                   : 'bagaimana',
    'gmana'                       : 'bagaimana',
    'gmn'                         : 'bagaimana',
    'bagaimanapun'                : 'bagaimanapun',
    'bagikan'                     : 'bagikan',
    'repost'                      : 'bagikan',
    'retweet'                     : 'bagikan',
    'share'                       : 'bagikan',
    'shere'                       : 'bagikan',
    'apik'                        : 'bagus',
    'awesome'                     : 'bagus',
    'bagus'                       : 'bagus',
    'baguss'                      : 'bagus',
    'bagussss'                    : 'bagus',
    'baguus'                      : 'bagus',
    'baguuss'                     : 'bagus',
    'bgs'                         : 'bagus',
    'bgss'                        : 'bagus',
    'bgus'                        : 'bagus',
    'bgusss'                      : 'bagus',
    'ciamik'                      : 'bagus',
    'gg'                          : 'bagus',
    'good'                        : 'bagus',
    'gooood'                      : 'bagus',
    'great'                       : 'bagus',
    'gud'                         : 'bagus',
    'jos'                         : 'bagus',
    'joss'                        : 'bagus',
    'josss'                       : 'bagus',
    'jossss'                      : 'bagus',
    'jozz'                        : 'bagus',
    'nais'                        : 'bagus',
    'nice'                        : 'bagus',
    'bagus2'                      : 'bagus-bagus',
    'language'                    : 'bahasa',
    'bahkan'                      : 'bahkan',
    'even'                        : 'bahkan',
    'baik2'                       : 'baik-baik',
    'bangeet'                     : 'banget',
    'bangeett'                    : 'banget',
    'banget'                      : 'banget',
    'bangett'                     : 'banget',
    'bangt'                       : 'banget',
    'bget'                        : 'banget',
    'bgt'                         : 'banget',
    'bgtt'                        : 'banget',
    'bgttt'                       : 'banget',
    'bngat'                       : 'banget',
    'bnget'                       : 'banget',
    'bngett'                      : 'banget',
    'bngt'                        : 'banget',
    'bangga'                      : 'bangga',
    'proud'                       : 'bangga',
    'help'                        : 'bantuan',
    'bnyak'                       : 'banyak',
    'bnyk'                        : 'banyak',
    'byk'                         : 'banyak',
    'bug2'                        : 'banyak bug',
    'banjir iklan'                : 'banyak iklan',
    'iklan melulu'                : 'banyak iklan',
    'iklan mulu'                  : 'banyak iklan',
    'om'                          : 'bapak',
    'baru'                        : 'baru',
    'bru'                         : 'baru',
    'baru saja'                   : 'baru saja',
    'barusan'                     : 'baru saja',
    'database'                    : 'basis data',
    'db'                          : 'basis data',
    'fanbase'                     : 'basis penggemar',
    'fansbase'                    : 'basis penggemar',
    'bass'                        : 'bass',
    'batal'                       : 'batalkan',
    'cancel'                      : 'batalkan',
    'cancell'                     : 'batalkan',
    'kancell'                     : 'batalkan',
    'baterai'                     : 'baterai',
    'batere'                      : 'baterai',
    'batrai'                      : 'baterai',
    'batre'                       : 'baterai',
    'battery'                     : 'baterai',
    'lowbat'                      : 'baterai habis',
    'pay'                         : 'bayar',
    'auto pay'                    : 'bayar otomatis',
    'bebas iklan'                 : 'bebas iklan',
    'bbrapa'                      : 'beberapa',
    'bbrp'                        : 'beberapa',
    'work'                        : 'bekerja',
    'working'                     : 'bekerja',
    'works'                       : 'bekerja',
    'frozen'                      : 'beku',
    'ngefreeze'                   : 'beku',
    'belom'                       : 'belum',
    'belum'                       : 'belum',
    'blm'                         : 'belum',
    'blmm'                        : 'belum',
    'blom'                        : 'belum',
    'belum prnh'                  : 'belum pernah',
    'blm pernah'                  : 'belum pernah',
    'bener'                       : 'benar',
    'bnaran'                      : 'benar',
    'bner'                        : 'benar',
    'bnr'                         : 'benar',
    'valid'                       : 'benar',
    'bener2'                      : 'benar-benar',
    'benci'                       : 'benci',
    'hate'                        : 'benci',
    'feed'                        : 'beranda',
    'home'                        : 'beranda',
    'berat'                       : 'berat',
    'brt'                         : 'berat',
    'heavy'                       : 'berat',
    'sharing'                     : 'berbagi',
    'bahaya'                      : 'berbahaya',
    'dangerous'                   : 'berbahaya',
    'promoted'                    : 'berbayar',
    'plan'                        : 'berencana',
    'useful'                      : 'berguna',
    'harap'                       : 'berharap',
    'hope'                        : 'berharap',
    'wish'                        : 'berharap',
    'berhasil'                    : 'berhasil',
    'success'                     : 'berhasil',
    'unsub'                       : 'berhenti berlangganan',
    'unfollow'                    : 'berhenti ikut',
    'unfollow artis'              : 'berhenti mengikuti artis',
    'unlike lagu'                 : 'berhenti menyukai lagu',
    'lmk'                         : 'beritahu saya',
    'bilang'                      : 'berkata',
    'blg'                         : 'berkata',
    'blng'                        : 'berkata',
    'ngomong'                     : 'berkata',
    'ngomong2'                    : 'berkata-kata',
    'berlangganan'                : 'berlangganan',
    'langganan'                   : 'berlangganan',
    'lngnn'                       : 'berlangganan',
    'sub'                         : 'berlangganan',
    'subcribe'                    : 'berlangganan',
    'subs'                        : 'berlangganan',
    'subscribe'                   : 'berlangganan',
    'daftar premium'              : 'berlangganan premium',
    'lebay'                       : 'berlebihan',
    'bermanfaat'                  : 'bermanfaat',
    'niat'                        : 'berniat',
    'muter2'                      : 'berputar-putar',
    'bareng'                      : 'bersama',
    'brng'                        : 'bersama',
    'feat'                        : 'bersama',
    'featuring'                   : 'bersama',
    'ft'                          : 'bersama',
    'clean'                       : 'bersih',
    'powerful'                    : 'bertenaga',
    'looping'                     : 'berulang',
    'gede'                        : 'besar',
    'gedee'                       : 'besar',
    'besok'                       : 'besok',
    'bsk'                         : 'besok',
    'bsok'                        : 'besok',
    'beta'                        : 'beta',
    'biasa'                       : 'biasa',
    'biasa saja'                  : 'biasa saja',
    'mediocre'                    : 'biasa saja',
    'so so'                       : 'biasa saja',
    'normally'                    : 'biasanya',
    'typically'                   : 'biasanya',
    'usually'                     : 'biasanya',
    'biaya'                       : 'biaya',
    'charge'                      : 'biaya',
    'cost'                        : 'biaya',
    'galau'                       : 'bimbang',
    'galauu'                      : 'bimbang',
    'bingung'                     : 'bingung',
    'confused'                    : 'bingung',
    'bintang'                     : 'bintang',
    'star'                        : 'bintang',
    'stars'                       : 'bintang',
    '5 bintang'                   : 'bintang lima',
    '5star'                       : 'bintang lima',
    'bintang 5'                   : 'bintang lima',
    'five star'                   : 'bintang lima',
    '1 bintang'                   : 'bintang satu',
    '1star'                       : 'bintang satu',
    'one star'                    : 'bintang satu',
    'bisa'                        : 'bisa',
    'biss'                        : 'bisa',
    'bs'                          : 'bisa',
    'bsa'                         : 'bisa',
    'bisa2'                       : 'bisa-bisa',
    'mute'                        : 'bisu',
    'bit rate'                    : 'bitrate',
    'bitrate'                     : 'bitrate',
    'blend'                       : 'blend',
    'bluetooth'                   : 'bluetooth',
    'spoiler'                     : 'bocoran',
    'bohong'                      : 'bohong',
    'bokis'                       : 'bohong',
    'boong'                       : 'bohong',
    'cap'                         : 'bohong',
    'boleh'                       : 'boleh',
    'may'                         : 'boleh',
    'boros'                       : 'boros',
    'broos'                       : 'boros',
    'boros kuota'                 : 'boros kuota',
    'bored'                       : 'bosan',
    'bosen'                       : 'bosan',
    'bro'                         : 'bro',
    'buffer'                      : 'buffering',
    'buffering'                   : 'buffering',
    'bug'                         : 'bug',
    'bugg'                        : 'bug',
    'bugs'                        : 'bug',
    'glitch'                      : 'bug',
    'bkak'                        : 'buka',
    'buka'                        : 'buka',
    'bukak'                       : 'buka',
    'buka cepat'                  : 'buka cepat',
    'open in'                     : 'buka di',
    'buka lama'                   : 'buka lama',
    'bkn'                         : 'bukan',
    'bukan'                       : 'bukan',
    'bukn'                        : 'bukan',
    'bln'                         : 'bulan',
    'bulanan'                     : 'bulanan',
    'monthly'                     : 'bulanan',
    'blurry'                      : 'buram',
    'awful'                       : 'buruk',
    'bad'                         : 'buruk',
    'bangkai'                     : 'buruk',
    'bangke'                      : 'buruk',
    'bruk'                        : 'buruk',
    'buruk'                       : 'buruk',
    'horrible'                    : 'buruk',
    'sampah'                      : 'buruk',
    'smph'                        : 'buruk',
    'tahi'                        : 'buruk',
    'tai'                         : 'buruk',
    'terrible'                    : 'buruk',
    'cache'                       : 'cache',
    'data cache'                  : 'cache data',
    'backup'                      : 'cadangan',
    'cloud backup'                : 'cadangan awan',
    'daily mix'                   : 'campuran harian',
    'advance'                     : 'canggih',
    'canggih'                     : 'canggih',
    'cnggh'                       : 'canggih',
    'canvas'                      : 'canvas spotify',
    'captcha'                     : 'captcha',
    'search'                      : 'cari',
    'vibe check'                  : 'cek suasana',
    'cepat'                       : 'cepat',
    'cpet'                        : 'cepat',
    'cpt'                         : 'cepat',
    'fast'                        : 'cepat',
    'ngebut'                      : 'cepat',
    'ngegas'                      : 'cepat',
    'cepat respon'                : 'cepat menanggapi',
    'cepet2'                      : 'cepat-cepat',
    'stories'                     : 'cerita',
    'story'                       : 'cerita',
    'chromecast'                  : 'chromecast',
    'cinta'                       : 'cinta',
    'try'                         : 'coba',
    'cucok'                       : 'cocok',
    'crash'                       : 'crash',
    'crass'                       : 'crash',
    'ngecrash'                    : 'crash',
    'crossfade'                   : 'crossfade',
    'pinch'                       : 'cubit',
    'cukup'                       : 'cukup',
    'lumayan'                     : 'cukup baik',
    'lumayan bagus'               : 'cukup baik',
    'daftar'                      : 'daftar',
    'register'                    : 'daftar',
    'signup'                      : 'daftar',
    'dan'                         : 'dan',
    'plus'                        : 'dan',
    'serta'                       : 'dan',
    'dkk'                         : 'dan kawan-kawan',
    'dll'                         : 'dan lain-lain',
    'dsb'                         : 'dan sebagainya',
    'dana'                        : 'dana',
    'dapat'                       : 'dapat',
    'dpat'                        : 'dapat',
    'dpt'                         : 'dapat',
    'accessible'                  : 'dapat diakses',
    'dr'                          : 'dari',
    'dri'                         : 'dari',
    'data'                        : 'data',
    'data aman'                   : 'data aman',
    'data bocor'                  : 'data bocor',
    'auto debit'                  : 'debit otomatis',
    'deezer'                      : 'deezer',
    'dg'                          : 'dengan',
    'dgn'                         : 'dengan',
    'dng'                         : 'dengan',
    'dngan'                       : 'dengan',
    'dengan demikian'             : 'dengan demikian',
    'desain bagus'                : 'desain bagus',
    'desain jelek'                : 'desain buruk',
    'irl'                         : 'di kehidupan nyata',
    'beliau'                      : 'dia',
    'dia'                         : 'dia',
    'doi'                         : 'dia',
    'dy'                          : 'dia',
    'dya'                         : 'dia',
    'cancelled'                   : 'dibatalkan',
    'made for you'                : 'dibuat untukmu',
    'supported'                   : 'didukung',
    'dihapus'                     : 'dihapus',
    'removed'                     : 'dihapus',
    'allowed'                     : 'diizinkan',
    'returned'                    : 'dikembalikan',
    'nerf'                        : 'dilemahkan',
    'dman'                        : 'dimana',
    'dmn'                         : 'dimana',
    'mana'                        : 'dimana',
    'rated'                       : 'dinilai',
    'dipake'                      : 'dipakai',
    'dipakein'                    : 'dipakai',
    'dipaksa'                     : 'dipaksa',
    'fixed'                       : 'diperbaiki',
    'improved'                    : 'diperbaiki',
    'patched'                     : 'diperbaiki',
    'updated'                     : 'diperbarui',
    'buff'                        : 'diperkuat',
    'needed'                      : 'diperlukan',
    'diputar'                     : 'diputar',
    'diputer'                     : 'diputar',
    'recommended'                 : 'direkomendasikan',
    'diskon'                      : 'diskon',
    'sponsored'                   : 'disponsori',
    'liked'                       : 'disukai',
    'added'                       : 'ditambah',
    'found'                       : 'ditemukan',
    'upgraded'                    : 'ditingkatkan',
    'changed'                     : 'diubah',
    'on repeat'                   : 'diulang',
    'dong'                        : 'dong',
    'dongg'                       : 'dong',
    'support'                     : 'dukungan',
    'dl'                          : 'dulu',
    'dlu'                         : 'dulu',
    'dulu'                        : 'dulu',
    'duo'                         : 'duo',
    'earphone'                    : 'earphone',
    'effective'                   : 'efektif',
    'efficient'                   : 'efisien',
    'exclusive'                   : 'eksklusif',
    'email'                       : 'email',
    'gmail'                       : 'email',
    'enak'                        : 'enak',
    'nak'                         : 'enak',
    'encryption'                  : 'enkripsi',
    'episode'                     : 'episode',
    'eps'                         : 'episode',
    'eq'                          : 'equalizer',
    'equaliser'                   : 'equalizer',
    'equalizer'                   : 'equalizer',
    'eror'                        : 'error',
    'err'                         : 'error',
    'error'                       : 'error',
    'errror'                      : 'error',
    'error2'                      : 'error-error',
    'aesthetic'                   : 'estetik',
    'eta'                         : 'estimasi waktu tiba',
    'facebook'                    : 'facebook',
    'fb'                          : 'facebook',
    'feature'                     : 'fitur',
    'features'                    : 'fitur',
    'fitur'                       : 'fitur',
    'fiture'                      : 'fitur',
    'fitur2'                      : 'fitur-fitur',
    'flac'                        : 'flac',
    'fleksibel'                   : 'fleksibel',
    'flexible'                    : 'fleksibel',
    'pp'                          : 'foto profil',
    'profile pic'                 : 'foto profil',
    'freemium'                    : 'freemium',
    'freeze'                      : 'freeze',
    'frustrasi'                   : 'frustrasi',
    'function'                    : 'fungsi',
    'fungsi'                      : 'fungsi',
    'fail'                        : 'gagal',
    'failed'                      : 'gagal',
    'gagal'                       : 'gagal',
    'zonk'                        : 'gagal',
    'thumbnail'                   : 'gambar mini',
    'down'                        : 'gangguan',
    'ganti'                       : 'ganti',
    'switch'                      : 'ganti',
    'gembira'                     : 'gembira',
    'genre'                       : 'genre',
    'gercep'                      : 'gerak cepat',
    'geser'                       : 'geser',
    'swipe'                       : 'geser',
    'gb'                          : 'gigabyte',
    'gila'                        : 'gila',
    'gilaa'                       : 'gila',
    'gilee'                       : 'gila',
    'gileee'                      : 'gila',
    'gils'                        : 'gila',
    'google play'                 : 'google play store',
    'play store'                  : 'google play store',
    'playstore'                   : 'google play store',
    'gopay'                       : 'gopay',
    'cuma-cuma'                   : 'gratis',
    'free'                        : 'gratis',
    'gratis'                      : 'gratis',
    'gratisan'                    : 'gratis',
    'gretong'                     : 'gratis',
    'percuma'                     : 'gratis',
    'abis'                        : 'habis',
    'abiss'                       : 'habis',
    'abissss'                     : 'habis',
    'hai'                         : 'halo',
    'halo'                        : 'halo',
    'hello'                       : 'halo',
    'hey'                         : 'halo',
    'hi'                          : 'halo',
    'hampir'                      : 'hampir',
    'hmpr'                        : 'hampir',
    'ancur'                       : 'hancur',
    'ancurr'                      : 'hancur',
    'hancur'                      : 'hancur',
    'hang'                        : 'hang',
    'ngehang'                     : 'hang',
    'hanya'                       : 'hanya',
    'just'                        : 'hanya',
    'only'                        : 'hanya',
    'delete'                      : 'hapus',
    'hapus'                       : 'hapus',
    'remove'                      : 'hapus',
    'uninstall'                   : 'hapus',
    'harga'                       : 'harga',
    'price'                       : 'harga',
    'bayar mahal'                 : 'harga mahal',
    'harga naik'                  : 'harga naik',
    'harga stabil'                : 'harga stabil',
    'harga murah'                 : 'harga terjangkau',
    'hr'                          : 'hari',
    'daily'                       : 'harian',
    'harus'                       : 'harus',
    'hrs'                         : 'harus',
    'hrus'                        : 'harus',
    'must'                        : 'harus',
    'hati2'                       : 'hati-hati',
    'headphone'                   : 'headphone',
    'headset'                     : 'headset',
    'data saver'                  : 'hemat data',
    'hemat kuota'                 : 'hemat kuota',
    'heran'                       : 'heran',
    'hi-fi'                       : 'hi-fi',
    'hifi'                        : 'hi-fi',
    'lose'                        : 'hilang',
    'lost'                        : 'hilang',
    'missing'                     : 'hilang',
    'hoax'                        : 'hoaks',
    'contact us'                  : 'hubungi kami',
    'hmu'                         : 'hubungi saya',
    'ideal'                       : 'ideal',
    'ad'                          : 'iklan',
    'ads'                         : 'iklan',
    'advertisement'               : 'iklan',
    'iklan'                       : 'iklan',
    'iklan ganggu'                : 'iklan mengganggu',
    'iklan panjang'               : 'iklan panjang',
    'iklan ga bisa diskip'        : 'iklan tidak bisa dilewati',
    'iklan2'                      : 'iklan-iklan',
    'follow'                      : 'ikut',
    'individual'                  : 'individu',
    'influencer'                  : 'influencer',
    'mau'                         : 'ingin',
    'mw'                          : 'ingin',
    'pengen'                      : 'ingin',
    'pengin'                      : 'ingin',
    'pgn'                         : 'ingin',
    'pingin'                      : 'ingin',
    'pngen'                       : 'ingin',
    'want'                        : 'ingin',
    'kepo'                        : 'ingin tahu',
    'kpo'                         : 'ingin tahu',
    'nih'                         : 'ini',
    'innalillahi'                 : 'innalillahi',
    'innovative'                  : 'inovatif',
    'inovatif'                    : 'inovatif',
    'ig'                          : 'instagram',
    'insta'                       : 'instagram',
    'instagram'                   : 'instagram',
    'instan'                      : 'instan',
    'instant'                     : 'instan',
    'internet'                    : 'internet',
    'internet kencang'            : 'internet cepat',
    'internet lemah'              : 'internet lemah',
    'intuitif'                    : 'intuitif',
    'intuitive'                   : 'intuitif',
    'ios'                         : 'ios',
    'iphone'                      : 'iphone',
    'tuh'                         : 'itu',
    'permission'                  : 'izin',
    'izin berlebihan'             : 'izin berlebihan',
    'jadi'                        : 'jadi',
    'jd'                          : 'jadi',
    'jdi'                         : 'jadi',
    "don't"                       : 'jangan',
    'dont'                        : 'jangan',
    'jan'                         : 'jangan',
    'jangan'                      : 'jangan',
    'jangankan'                   : 'jangan',
    'jgn'                         : 'jangan',
    'jgnn'                        : 'jangan',
    'jarang'                      : 'jarang',
    'jrng'                        : 'jarang',
    'rarely'                      : 'jarang',
    'network'                     : 'jaringan',
    'jauh lebih baik'             : 'jauh lebih baik',
    'much better'                 : 'jauh lebih baik',
    'jauh lebih buruk'            : 'jauh lebih buruk',
    'explore'                     : 'jelajahi',
    'clear'                       : 'jelas',
    'jelas'                       : 'jelas',
    'jelek'                       : 'jelek',
    'jelekk'                      : 'jelek',
    'jlek'                        : 'jelek',
    'jelek2'                      : 'jelek-jelek',
    'pop up'                      : 'jendela pop-up',
    'popup'                       : 'jendela pop-up',
    'iirc'                        : 'jika saya ingat dengan benar',
    'joox'                        : 'joox',
    'also'                        : 'juga',
    'jg'                          : 'juga',
    'juga'                        : 'juga',
    'too'                         : 'juga',
    'tbh'                         : 'jujur saja',
    'jt'                          : 'juta',
    'berantakan'                  : 'kacau',
    'chaos'                       : 'kacau',
    'kacau'                       : 'kacau',
    'kadang'                      : 'kadang',
    'kdng'                        : 'kadang',
    'kadang2'                     : 'kadang-kadang',
    'sometimes'                   : 'kadang-kadang',
    'kk'                          : 'kakak',
    'rigid'                       : 'kaku',
    'kalo'                        : 'kalau',
    'klo'                         : 'kalau',
    'klu'                         : 'kalau',
    'elu2'                        : 'kalian',
    'kalian'                      : 'kalian',
    'kln'                         : 'kalian',
    'kmua'                        : 'kalian',
    'kmi'                         : 'kami',
    'elo'                         : 'kamu',
    'elu'                         : 'kamu',
    'ente'                        : 'kamu',
    'km'                          : 'kamu',
    'kmu'                         : 'kamu',
    'koe'                         : 'kamu',
    'lo'                          : 'kamu',
    'loe'                         : 'kamu',
    'loee'                        : 'kamu',
    'lu'                          : 'kamu',
    'lueeh'                       : 'kamu',
    'lw'                          : 'kamu',
    'u'                           : 'kamu',
    'kan'                         : 'kan',
    'kapn'                        : 'kapan',
    'kpn'                         : 'kapan',
    'main character'              : 'karakter utama',
    'karana'                      : 'karena',
    'karena'                      : 'karena',
    'karna'                       : 'karena',
    'krn'                         : 'karena',
    'krna'                        : 'karena',
    'sebab'                       : 'karena',
    'soal'                        : 'karena',
    'soalnya'                     : 'karena',
    'rizz'                        : 'karisma',
    'kartu debit'                 : 'kartu debit',
    'cc'                          : 'kartu kredit',
    'kartu kredit'                : 'kartu kredit',
    'pass'                        : 'kata sandi',
    'passwd'                      : 'kata sandi',
    'password'                    : 'kata sandi',
    'sultan'                      : 'kaya',
    'kbps'                        : 'kbps',
    'security'                    : 'keamanan',
    'keamanan bagus'              : 'keamanan baik',
    'keamanan lemah'              : 'keamanan lemah',
    'speed'                       : 'kecepatan',
    'ai'                          : 'kecerdasan buatan',
    'disappointed'                : 'kecewa',
    'kcwa'                        : 'kecewa',
    'kecewa'                      : 'kecewa',
    'kecil'                       : 'kecil',
    'mungil'                      : 'kecil',
    'kec'                         : 'kecuali',
    'kedua'                       : 'kedua',
    'plot twist'                  : 'kejutan',
    'loudness'                    : 'kekerasan',
    'keluar'                      : 'keluar',
    'kluar'                       : 'keluar',
    'log out'                     : 'keluar',
    'logout'                      : 'keluar',
    'ngedropout'                  : 'keluar',
    'signout'                     : 'keluar',
    'famili'                      : 'keluarga',
    'complain'                    : 'keluhan',
    'complaint'                   : 'keluhan',
    'keluhan'                     : 'keluhan',
    'kemaren'                     : 'kemarin',
    'kemarin'                     : 'kemarin',
    'kmrn'                        : 'kemarin',
    'rollback'                    : 'kembali ke versi sebelumnya',
    'kembaliin'                   : 'kembalikan',
    'return'                      : 'kembalikan',
    'kenapa'                      : 'kenapa',
    'knapa'                       : 'kenapa',
    'knp'                         : 'kenapa',
    'napa'                        : 'kenapa',
    'ngapa'                       : 'kenapa',
    'kpd'                         : 'kepada',
    'kpda'                        : 'kepada',
    'kepuasan'                    : 'kepuasan',
    'cool'                        : 'keren',
    'kece'                        : 'keren',
    'kereeen'                     : 'keren',
    'kereen'                      : 'keren',
    'keren'                       : 'keren',
    'kerenn'                      : 'keren',
    'kren'                        : 'keren',
    'krj'                         : 'kerja',
    'bete'                        : 'kesal',
    'bt'                          : 'kesal',
    'kesal'                       : 'kesal',
    'kesel'                       : 'kesal',
    'sebel'                       : 'kesal',
    'caption'                     : 'keterangan',
    'ketiga'                      : 'ketiga',
    'tap'                         : 'ketuk',
    'double tap'                  : 'ketuk dua kali',
    'cuan'                        : 'keuntungan',
    'khawatir'                    : 'khawatir',
    'particularly'                : 'khususnya',
    'send'                        : 'kirim',
    'kt'                          : 'kita',
    'qta'                         : 'kita',
    'kita2'                       : 'kita semua',
    'click'                       : 'klik',
    'klik'                        : 'klik',
    'pencet'                      : 'klik',
    'otp'                         : 'kode otp',
    'kode promo'                  : 'kode promosi',
    'ko'                          : 'kok',
    'kok'                         : 'kok',
    'koq'                         : 'kok',
    'qok'                         : 'kok',
    'collab'                      : 'kolaborasi',
    'collaboration'               : 'kolaborasi',
    'kolaborasi'                  : 'kolaborasi',
    'koleksi'                     : 'koleksi',
    'comment'                     : 'komentar',
    'komen'                       : 'komentar',
    'komentar'                    : 'komentar',
    'compatible'                  : 'kompatibel',
    'pc'                          : 'komputer',
    'community'                   : 'komunitas',
    'connect'                     : 'koneksi',
    'connection'                  : 'koneksi',
    'koneksi'                     : 'koneksi',
    'fakir sinyal'                : 'koneksi lemah',
    'concert'                     : 'konser',
    'kontak'                      : 'kontak',
    'content'                     : 'konten',
    'kreatif'                     : 'kreatif',
    'creator'                     : 'kreator',
    'kritik'                      : 'kritik',
    'quality'                     : 'kualitas',
    'kualitas audio'              : 'kualitas audio',
    'kualitas premium'            : 'kualitas premium',
    'low quality'                 : 'kualitas rendah',
    'kualitas suara'              : 'kualitas suara',
    'kualitas suara bagus'        : 'kualitas suara baik',
    'high quality'                : 'kualitas tinggi',
    'kuno'                        : 'kuno',
    'kuota habis'                 : 'kuota habis',
    'coupon'                      : 'kupon',
    'krang'                       : 'kurang',
    'krg'                         : 'kurang',
    'krng'                        : 'kurang',
    'kurang'                      : 'kurang',
    'kurg'                        : 'kurang',
    'lag'                         : 'lag',
    'lagg'                        : 'lag',
    'lagger'                      : 'lag',
    'laggy'                       : 'lag',
    'lags'                        : 'lag',
    'ngelag'                      : 'lag',
    'again'                       : 'lagi',
    'lagi'                        : 'lagi',
    'lg'                          : 'lagi',
    'lgi'                         : 'lagi',
    'lgu'                         : 'lagu',
    'song'                        : 'lagu',
    'songs'                       : 'lagu',
    'next track'                  : 'lagu berikutnya',
    'cover'                       : 'lagu daur ulang',
    'cover song'                  : 'lagu daur ulang',
    'earworm'                     : 'lagu yang sulit dilupakan',
    'lagu2'                       : 'lagu-lagu',
    'lahh'                        : 'lah',
    'gaskeun'                     : 'lakukan saja',
    'gaspol'                      : 'lakukan saja',
    'lama'                        : 'lama',
    'lmaa'                        : 'lama',
    'lambat'                      : 'lambat',
    'lelet'                       : 'lambat',
    'lemot'                       : 'lambat',
    'llelet'                      : 'lambat',
    'lmbt'                        : 'lambat',
    'lmot'                        : 'lambat',
    'slow'                        : 'lambat',
    'lambat respon'               : 'lambat menanggapi',
    'lancar'                      : 'lancar',
    'lncar'                       : 'lancar',
    'smoot'                       : 'lancar',
    'smooth'                      : 'lancar',
    'smoth'                       : 'lancar',
    'subscription'                : 'langganan',
    'auto'                        : 'langsung',
    'direct'                      : 'langsung',
    'gaspool'                     : 'langsung',
    'langsung'                    : 'langsung',
    'live'                        : 'langsung',
    'lngsng'                      : 'langsung',
    'lanjut'                      : 'lanjut',
    'lnjt'                        : 'lanjut',
    'next'                        : 'lanjut',
    'laporan'                     : 'laporan',
    'report'                      : 'laporan',
    'laptop'                      : 'laptop',
    'cs'                          : 'layanan pelanggan',
    'customer service'            : 'layanan pelanggan',
    'layar'                       : 'layar',
    'screen'                      : 'layar',
    'better'                      : 'lebih baik',
    'mending'                     : 'lebih baik',
    'mendingan'                   : 'lebih baik',
    'lebih buruk'                 : 'lebih buruk',
    'lebih parah'                 : 'lebih buruk',
    'worse'                       : 'lebih buruk',
    'prefer'                      : 'lebih suka',
    'lega'                        : 'lega',
    'relieved'                    : 'lega',
    'cape'                        : 'lelah',
    'capek'                       : 'lelah',
    'cpek'                        : 'lelah',
    'lelah'                       : 'lelah',
    'tired'                       : 'lelah',
    'lengkap'                     : 'lengkap',
    'lngkp'                       : 'lengkap',
    'drop'                        : 'lepas',
    'lewat'                       : 'lewati',
    'skip'                        : 'lewati',
    'iklan skip'                  : 'lewati iklan',
    'lho'                         : 'lho',
    'loh'                         : 'lho',
    'line'                        : 'line',
    'timeline'                    : 'linimasa',
    'linkaja'                     : 'linkaja',
    'cross platform'              : 'lintas platform',
    'lirik'                       : 'lirik',
    'lyric'                       : 'lirik',
    'lyrics'                      : 'lirik',
    'loading cepat'               : 'loading cepat',
    'loading lama'                : 'loading lama',
    'lossless'                    : 'lossless',
    'amazing'                     : 'luar biasa',
    'king'                        : 'luar biasa',
    'masya allah'                 : 'luar biasa',
    'masyaallah'                  : 'luar biasa',
    'queen'                       : 'luar biasa',
    'slay'                        : 'luar biasa',
    'subhanallah'                 : 'luar biasa',
    'lol'                         : 'lucu',
    'lupa'                        : 'lupa',
    'maaf'                        : 'maaf',
    'maf'                         : 'maaf',
    'sori'                        : 'maaf',
    'sorry'                       : 'maaf',
    'sory'                        : 'maaf',
    'sry'                         : 'maaf',
    'mac'                         : 'mac',
    'macbook'                     : 'macbook',
    'macet'                       : 'macet',
    'ngadat'                      : 'macet',
    'stuck'                       : 'macet',
    'ngadat lagi'                 : 'macet lagi',
    'expensive'                   : 'mahal',
    'mahal'                       : 'mahal',
    'mhal'                        : 'mahal',
    'mihil'                       : 'mahal',
    'all out'                     : 'maksimal',
    'allout'                      : 'maksimal',
    'maksimal'                    : 'maksimal',
    'maximal'                     : 'maksimal',
    'maksimum'                    : 'maksimum',
    'maximum'                     : 'maksimum',
    'mksd'                        : 'maksud',
    'maksudnya'                   : 'maksudnya',
    'instead'                     : 'malahan',
    'malah'                       : 'malahan',
    'malahan'                     : 'malahan',
    'lazy'                        : 'malas',
    'malas'                       : 'malas',
    'males'                       : 'malas',
    'mls'                         : 'malas',
    'mager'                       : 'malas bergerak',
    'able'                        : 'mampu',
    'mampu'                       : 'mampu',
    'manfaat'                     : 'manfaat',
    'mantaap'                     : 'mantap',
    'mantab'                      : 'mantap',
    'mantapp'                     : 'mantap',
    'mantappp'                    : 'mantap',
    'mantep'                      : 'mantap',
    'mntap'                       : 'mantap',
    'mntapp'                      : 'mantap',
    'mntappp'                     : 'mantap',
    'mantul'                      : 'mantap betul',
    'angry'                       : 'marah',
    'marah'                       : 'marah',
    'binge'                       : 'maraton mendengarkan',
    'mas'                         : 'mas',
    'masa'                        : 'masa',
    'masak'                       : 'masak',
    'issue'                       : 'masalah',
    'issues'                      : 'masalah',
    'problem'                     : 'masalah',
    'masi'                        : 'masih',
    'msh'                         : 'masih',
    'msih'                        : 'masih',
    'masing2'                     : 'masing-masing',
    'log in'                      : 'masuk',
    'login'                       : 'masuk',
    'msk'                         : 'masuk',
    'signin'                      : 'masuk',
    'feedback'                    : 'masukan',
    'masukan'                     : 'masukan',
    'currency'                    : 'mata uang',
    'mati'                        : 'mati',
    'matik'                       : 'mati',
    'mati sendiri'                : 'mati sendiri',
    'kematian mendadak'           : 'mati tiba-tiba',
    'turn off'                    : 'matikan',
    'mbak'                        : 'mbak',
    'mbps'                        : 'mbps',
    'mb'                          : 'megabyte',
    'helpdesk'                    : 'meja bantuan',
    'lapor'                       : 'melaporkan',
    'ngereport'                   : 'melaporkan',
    'lht'                         : 'melihat',
    'liat'                        : 'melihat',
    'liatin'                      : 'melihat',
    'lihat'                       : 'melihat',
    'liot'                        : 'melihat',
    'lupain'                      : 'melupakan',
    'makai'                       : 'memakai',
    'make'                        : 'memakai',
    'pake'                        : 'memakai',
    'emang'                       : 'memang',
    'emg'                         : 'memang',
    'mmg'                         : 'memang',
    'ngeinstall'                  : 'memasang',
    'matiin'                      : 'mematikan',
    'ngeshare'                    : 'membagikan',
    'share lagu'                  : 'membagikan lagu',
    'ngebandingin'                : 'membandingkan',
    'bantu'                       : 'membantu',
    'bantuin'                     : 'membantu',
    'bntu'                        : 'membantu',
    'ngebantu'                    : 'membantu',
    'bayar'                       : 'membayar',
    'bayarin'                     : 'membayar',
    'byr'                         : 'membayar',
    'bayar premium'               : 'membayar premium',
    'beli'                        : 'membeli',
    'beliin'                      : 'membeli',
    'bli'                         : 'membeli',
    'kasih'                       : 'memberi',
    'kasihin'                     : 'memberi',
    'ksh'                         : 'memberi',
    'confusing'                   : 'membingungkan',
    'membingungkan'               : 'membingungkan',
    'ngeblock'                    : 'memblokir',
    'zz'                          : 'membosankan',
    'zzz'                         : 'membosankan',
    'frustrating'                 : 'membuat frustasi',
    'cliffhanger'                 : 'membuat penasaran',
    'bikin playlist'              : 'membuat playlist',
    'butuh'                       : 'membutuhkan',
    'need'                        : 'membutuhkan',
    'cek'                         : 'memeriksa',
    'ngecek'                      : 'memeriksa',
    'minta'                       : 'meminta',
    'mintain'                     : 'meminta',
    'mnta'                        : 'meminta',
    'minta tolong'                : 'meminta bantuan',
    'minta izin'                  : 'meminta izin',
    'memori'                      : 'memori',
    'memory'                      : 'memori',
    'ngepatch'                    : 'memperbaiki',
    'ngeupdate'                   : 'memperbarui',
    'load'                        : 'memuat',
    'loading'                     : 'memuat',
    'ngeload'                     : 'memuat',
    'muter'                       : 'memutar',
    'muterin'                     : 'memutar',
    'muter lagu'                  : 'memutar lagu',
    'putar lagu'                  : 'memutar lagu',
    'stunning'                    : 'menakjubkan',
    'cengeng'                     : 'menangis',
    'ngebackup'                   : 'mencadangkan',
    'cari'                        : 'mencari',
    'cariin'                      : 'mencari',
    'nyari'                       : 'mencari',
    'cari lagu'                   : 'mencari lagu',
    'attempt'                     : 'mencoba',
    'coba'                        : 'mencoba',
    'cobain'                      : 'mencoba',
    'nyoba'                       : 'mencoba',
    'ngelist'                     : 'mendaftar',
    'dapet'                       : 'mendapat',
    'dapetin'                     : 'mendapat',
    'dpet'                        : 'mendapat',
    'denger'                      : 'mendengar',
    'dengerin'                    : 'mendengar',
    'dnger'                       : 'mendengar',
    'dngr'                        : 'mendengar',
    'dengerin lagu'               : 'mendengarkan lagu',
    'nemu'                        : 'menemukan',
    'nemuin'                      : 'menemukan',
    'nemu lagu'                   : 'menemukan lagu',
    'edit playlist'               : 'mengedit playlist',
    'gerutu'                      : 'mengeluh',
    'komplain'                    : 'mengeluh',
    'ngedumel'                    : 'mengeluh',
    'ngerti'                      : 'mengerti',
    'tau selera'                  : 'mengerti selera',
    'disturbing'                  : 'mengganggu',
    'ganggu'                      : 'mengganggu',
    'ngeganggu'                   : 'mengganggu',
    'gantiin'                     : 'mengganti',
    'swiping'                     : 'menggeser',
    'nge-scroll'                  : 'menggulir',
    'scroll'                      : 'menggulir',
    'scrolling'                   : 'menggulir',
    'using'                       : 'menggunakan',
    'hapus lagu'                  : 'menghapus lagu',
    'hapus playlist'              : 'menghapus playlist',
    'expect'                      : 'mengharapkan',
    'hubungi'                     : 'menghubungi',
    'following'                   : 'mengikuti',
    'ngefollow'                   : 'mengikuti',
    'follow artis'                : 'mengikuti artis',
    'kirim'                       : 'mengirim',
    'kirimin'                     : 'mengirim',
    'ngerubah'                    : 'mengubah',
    'ngerestart'                  : 'mengulang',
    'ngedownload'                 : 'mengunduh',
    'ngepost'                     : 'mengunggah',
    'ngeupload'                   : 'mengunggah',
    'posting'                     : 'mengunggah',
    'enjoy'                       : 'menikmati',
    'enjoying'                    : 'menikmati',
    'najis'                       : 'menjijikkan',
    'menu'                        : 'menu',
    'menu rumit'                  : 'menu rumit',
    'menu simple'                 : 'menu sederhana',
    'nggu'                        : 'menunggu',
    'nunggu'                      : 'menunggu',
    'tnggu'                       : 'menunggu',
    'tunggu'                      : 'menunggu',
    'demand'                      : 'menuntut',
    'tuntut'                      : 'menuntut',
    'imo'                         : 'menurut saya',
    'imho'                        : 'menurut saya yang rendah hati',
    'nutup'                       : 'menutup',
    'nyala'                       : 'menyala',
    'nyalain'                     : 'menyalakan',
    'annoying'                    : 'menyebalkan',
    'anoy'                        : 'menyebalkan',
    'menyebalkan'                 : 'menyebalkan',
    'ngehe'                       : 'menyebalkan',
    'nyebel'                      : 'menyebalkan',
    'nyebelin'                    : 'menyebalkan',
    'asik'                        : 'menyenangkan',
    'asyik'                       : 'menyenangkan',
    'seru'                        : 'menyenangkan',
    'sruu'                        : 'menyenangkan',
    'wholesome'                   : 'menyenangkan',
    'nyimpen'                     : 'menyimpan',
    'simpen'                      : 'menyimpan',
    'save lagu'                   : 'menyimpan lagu',
    'ngesync'                     : 'menyinkronkan',
    'ngelike'                     : 'menyukai',
    'like lagu'                   : 'menyukai lagu',
    'ngerasain'                   : 'merasakan',
    'merch'                       : 'merchandise',
    'mreka'                       : 'mereka',
    'mrk'                         : 'mereka',
    'recording'                   : 'merekam',
    'ngerusak'                    : 'merusak',
    'although'                    : 'meskipun',
    'biarpun'                     : 'meskipun',
    'despite'                     : 'meskipun',
    'in spite of'                 : 'meskipun',
    'kendati'                     : 'meskipun',
    'meski'                       : 'meskipun',
    'meskipun'                    : 'meskipun',
    'sekalipun'                   : 'meskipun',
    'sungguhpun'                  : 'meskipun',
    'walau'                       : 'meskipun',
    'walaupun'                    : 'meskipun',
    'microphone'                  : 'mikrofon',
    'mnggu'                       : 'minggu',
    'weekly'                      : 'mingguan',
    'minim'                       : 'minim',
    'minimal'                     : 'minimal',
    'minimum'                     : 'minimum',
    'eg'                          : 'misalnya',
    'for example'                 : 'misalnya',
    'for instance'                : 'misalnya',
    'mode'                        : 'mode',
    'dark mode'                   : 'mode gelap',
    'darkmode'                    : 'mode gelap',
    'night mode'                  : 'mode gelap',
    'car mode'                    : 'mode mobil',
    'offline mode'                : 'mode offline',
    'online mode'                 : 'mode online',
    'light mode'                  : 'mode terang',
    'modern'                      : 'modern',
    'mhn'                         : 'mohon',
    'mohon'                       : 'mohon',
    'please'                      : 'mohon',
    'pliis'                       : 'mohon',
    'pliss'                       : 'mohon',
    'pls'                         : 'mohon',
    'plz'                         : 'mohon',
    'mono'                        : 'mono',
    'mp3'                         : 'mp3',
    'reload'                      : 'muat ulang',
    'ez'                          : 'mudah',
    'gampang'                     : 'mudah',
    'gmpg'                        : 'mudah',
    'mudah'                       : 'mudah',
    'gampang dipake'              : 'mudah digunakan',
    'mudah dipake'                : 'mudah digunakan',
    'user friendly'               : 'mudah digunakan',
    'baper'                       : 'mudah terpengaruh perasaan',
    'bismillah'                   : 'mulai',
    'reboot'                      : 'mulai ulang',
    'restar'                      : 'mulai ulang',
    'restart'                     : 'mulai ulang',
    'mgkn'                        : 'mungkin',
    'mkin'                        : 'mungkin',
    'mngkn'                       : 'mungkin',
    'mrah'                        : 'murah',
    'murah'                       : 'murah',
    'terjangkau'                  : 'murah',
    'music'                       : 'musik',
    'musik'                       : 'musik',
    'username'                    : 'nama pengguna',
    'however'                     : 'namun',
    'nevertheless'                : 'namun demikian',
    'nanti'                       : 'nanti',
    'ntar'                        : 'nanti',
    'ntarr'                       : 'nanti',
    'navigasi'                    : 'navigasi',
    'navigation'                  : 'navigasi',
    'country'                     : 'negara',
    'btw'                         : 'ngomong-ngomong',
    'rate'                        : 'nilai',
    'deactivate'                  : 'nonaktifkan',
    'disable'                     : 'nonaktifkan',
    'normal'                      : 'normal',
    'normalization'               : 'normalisasi',
    'notif'                       : 'notifikasi',
    'notification'                : 'notifikasi',
    'notifikasi'                  : 'notifikasi',
    'notifs'                      : 'notifikasi',
    'turn on'                     : 'nyalakan',
    'unmute'                      : 'nyalakan suara',
    'comfort'                     : 'nyaman',
    'comfortable'                 : 'nyaman',
    'convenient'                  : 'nyaman',
    'nyaman'                      : 'nyaman',
    'nymn'                        : 'nyaman',
    'nyonya'                      : 'nyonya',
    'live chat'                   : 'obrolan langsung',
    'offline'                     : 'offline',
    'ogg'                         : 'ogg',
    'ok'                          : 'oke',
    'okay'                        : 'oke',
    'oke'                         : 'oke',
    'okee'                        : 'oke',
    'okey'                        : 'oke',
    'okk'                         : 'oke',
    'oleh karena itu'             : 'oleh karena itu',
    'therefore'                   : 'oleh karena itu',
    'thus'                        : 'oleh karena itu',
    'online'                      : 'online',
    'optimal'                     : 'optimal',
    'org'                         : 'orang',
    'orng'                        : 'orang',
    'original'                    : 'orisinal',
    'otomatis'                    : 'otomatis',
    'ovo'                         : 'ovo',
    'pd'                          : 'pada',
    'pda'                         : 'pada',
    'padahal'                     : 'padahal',
    'pdahal'                      : 'padahal',
    'pdahl'                       : 'padahal',
    'pdhl'                        : 'padahal',
    'paham'                       : 'paham',
    'pham'                        : 'paham',
    'pke'                         : 'pakai',
    'paket'                       : 'paket',
    'maksa'                       : 'paksa',
    'fc'                          : 'paksa tutup',
    'force close'                 : 'paksa tutup',
    'force_close'                 : 'paksa tutup',
    'plg'                         : 'paling',
    'pling'                       : 'paling',
    'fake'                        : 'palsu',
    'panik'                       : 'panik',
    'keyboard'                    : 'papan ketik',
    'paraaah'                     : 'parah',
    'parah'                       : 'parah',
    'prah'                        : 'parah',
    'prh'                         : 'parah',
    'instal'                      : 'pasang',
    'install'                     : 'pasang',
    'pasang'                      : 'pasang',
    'reinstall'                   : 'pasang ulang',
    'pasein'                      : 'pasangkan',
    'fix'                         : 'pasti',
    'fixx'                        : 'pasti',
    'kerjaan'                     : 'pekerjaan',
    'student'                     : 'pelajar',
    'pelan2'                      : 'pelan-pelan',
    'payment'                     : 'pembayaran',
    'machine learning'            : 'pembelajaran mesin',
    'hater'                       : 'pembenci',
    'maint'                       : 'pemeliharaan',
    'maintenance'                 : 'pemeliharaan',
    'opini'                       : 'pendapat',
    'pendapat'                    : 'pendapat',
    'ux'                          : 'pengalaman pengguna',
    'sleep timer'                 : 'pengatur tidur',
    'setiing'                     : 'pengaturan',
    'setting'                     : 'pengaturan',
    'settingan'                   : 'pengaturan',
    'settings'                    : 'pengaturan',
    'refund'                      : 'pengembalian dana',
    'fanboy'                      : 'penggemar fanatik',
    'stan'                        : 'penggemar fanatik',
    'user'                        : 'pengguna',
    'follower'                    : 'pengikut',
    'rating'                      : 'penilaian',
    'full'                        : 'penuh',
    'hopeful'                     : 'penuh harap',
    'penuh iklan'                 : 'penuh iklan',
    'penyanyi'                    : 'penyanyi',
    'singer'                      : 'penyanyi',
    'storage'                     : 'penyimpanan',
    'patch'                       : 'perbaikan',
    'hotfix'                      : 'perbaikan darurat',
    'improve'                     : 'perbaiki',
    'perbaiki'                    : 'perbaiki',
    'refresh'                     : 'perbarui',
    'up'                          : 'perbarui',
    'upd'                         : 'perbarui',
    'updet'                       : 'perbarui',
    'updt'                        : 'perbarui',
    'zoom'                        : 'perbesar',
    'percaya'                     : 'percaya',
    'trust'                       : 'percaya',
    'trial'                       : 'percobaan',
    'free trial'                  : 'percobaan gratis',
    'performace'                  : 'performa',
    'performance'                 : 'performa',
    'ngacir'                      : 'pergi cepat',
    'zoom out'                    : 'perkecil',
    'perlu'                       : 'perlu',
    'excuse me'                   : 'permisi',
    'permisi'                     : 'permisi',
    'renewal'                     : 'perpanjang',
    'auto renewal'                : 'perpanjang otomatis',
    'autorenewal'                 : 'perpanjang otomatis',
    'library'                     : 'perpustakaan',
    'percent'                     : 'persen',
    'persen'                      : 'persen',
    'prsen'                       : 'persen',
    'personal'                    : 'personal',
    'pertama'                     : 'pertama',
    'dm'                          : 'pesan langsung',
    'dms'                         : 'pesan langsung',
    'pm'                          : 'pesan pribadi',
    'pindah'                      : 'pindah',
    'pndah'                       : 'pindah',
    'pindahin'                    : 'pindahkan',
    'playlist'                    : 'playlist',
    'playlits'                    : 'playlist',
    'plist'                       : 'playlist',
    'plylst'                      : 'playlist',
    'collaborative playlist'      : 'playlist kolaborasi',
    'pocast'                      : 'podcast',
    'podcas'                      : 'podcast',
    'podcast'                     : 'podcast',
    'handphone'                   : 'ponsel',
    'hape'                        : 'ponsel',
    'hp'                          : 'ponsel',
    'smartphone'                  : 'ponsel',
    'hype'                        : 'populer',
    'hyped'                       : 'populer',
    'meta'                        : 'populer saat ini',
    'cut'                         : 'potong',
    'prem'                        : 'premium',
    'premiem'                     : 'premium',
    'premium'                     : 'premium',
    'premiun'                     : 'premium',
    'premum'                      : 'premium',
    'prm'                         : 'premium',
    'privacy'                     : 'privasi',
    'privasi terjaga'             : 'privasi terjaga',
    'privat'                      : 'privat',
    'private'                     : 'privat',
    'profesional'                 : 'profesional',
    'professional'                : 'profesional',
    'profil'                      : 'profil',
    'profile'                     : 'profil',
    'promo'                       : 'promosi',
    'proprietary'                 : 'proprietary',
    'protes'                      : 'protes',
    'protest'                     : 'protes',
    'puas'                        : 'puas',
    'satisfied'                   : 'puas',
    'public'                      : 'publik',
    'publik'                      : 'publik',
    'restore'                     : 'pulihkan',
    'pulsa'                       : 'pulsa',
    'server farm'                 : 'pusat data',
    'pusing2'                     : 'pusing',
    'puter'                       : 'putar',
    'autoplay'                    : 'putar otomatis',
    'disconnect'                  : 'putus',
    'hopeless'                    : 'putus asa',
    'release radar'               : 'radar rilisan',
    'ragu'                        : 'ragu',
    'rahasia'                     : 'rahasia',
    'ram'                         : 'ram',
    'friendly'                    : 'ramah',
    'record'                      : 'rekam',
    'recommendation'              : 'rekomendasi',
    'rekomendasi'                 : 'rekomendasi',
    'rekomendasi bagus'           : 'rekomendasi bagus',
    'rekomendasi jelek'           : 'rekomendasi buruk',
    'recommend'                   : 'rekomendasikan',
    'healing'                     : 'relaksasi',
    'remix'                       : 'remix',
    'rencana'                     : 'rencana',
    'responsif'                   : 'responsif',
    'responsive'                  : 'responsif',
    'resso'                       : 'resso',
    'k'                           : 'ribu',
    'rb'                          : 'ribu',
    'miss'                        : 'rindu',
    'light'                       : 'ringan',
    'ringan'                      : 'ringan',
    'tl;dr'                       : 'ringkasnya',
    'tldr'                        : 'ringkasnya',
    'history'                     : 'riwayat',
    'rugi'                        : 'rugi',
    'complicated'                 : 'rumit',
    'rbet'                        : 'rumit',
    'ribet'                       : 'rumit',
    'broken'                      : 'rusak',
    'rsak'                        : 'rusak',
    'rusak'                       : 'rusak',
    'atm'                         : 'saat ini',
    'patient'                     : 'sabar',
    'sabar'                       : 'sabar',
    'aj'                          : 'saja',
    'aja'                         : 'saja',
    'doang'                       : 'saja',
    'copy'                        : 'salin',
    'copy link'                   : 'salin tautan',
    'sm'                          : 'sama',
    'sama saja'                   : 'sama saja',
    'sama2'                       : 'sama-sama',
    'pair'                        : 'sambung',
    'ampe'                        : 'sampai',
    'ampek'                       : 'sampai',
    'hingga'                      : 'sampai',
    'sampai'                      : 'sampai',
    'sampe'                       : 'sampai',
    'smp'                         : 'sampai',
    'smpe'                        : 'sampai',
    'until'                       : 'sampai',
    'ampe2'                       : 'sampai-sampai',
    'amat'                        : 'sangat',
    'gildong'                     : 'sangat',
    'hyper'                       : 'sangat',
    'mega'                        : 'sangat',
    'sgt'                         : 'sangat',
    'super'                       : 'sangat',
    'ultra'                       : 'sangat',
    'bagus bgt'                   : 'sangat bagus',
    'very good'                   : 'sangat bagus',
    'beda banget'                 : 'sangat berbeda',
    'jauh berbeda'                : 'sangat berbeda',
    'very bad'                    : 'sangat buruk',
    'enak bgt'                    : 'sangat enak',
    'jelek bgt'                   : 'sangat jelek',
    'kecewa bgt'                  : 'sangat kecewa',
    'keren bgt'                   : 'sangat keren',
    'lambat bgt'                  : 'sangat lambat',
    'lmao'                        : 'sangat lucu',
    'mahal bgt'                   : 'sangat mahal',
    'mantap bgt'                  : 'sangat mantap',
    'murah bgt'                   : 'sangat murah',
    'nyaman bgt'                  : 'sangat nyaman',
    'parah bgt'                   : 'sangat parah',
    'sangat puas'                 : 'sangat puas',
    'ribet bgt'                   : 'sangat rumit',
    'senang bgt'                  : 'sangat senang',
    'susah bgt'                   : 'sangat sulit',
    'sanggup'                     : 'sanggup',
    'chill'                       : 'santai',
    'santai'                      : 'santai',
    'santuy'                      : 'santai',
    'saran'                       : 'saran',
    'bintang 1'                   : 'satu bintang',
    'satu2'                       : 'satu-satu',
    'ak'                          : 'saya',
    'aku'                         : 'saya',
    'ane'                         : 'saya',
    'gue'                         : 'saya',
    'gueee'                       : 'saya',
    'gw'                          : 'saya',
    'gw!'                         : 'saya',
    'gweh'                        : 'saya',
    'sy'                          : 'saya',
    'w'                           : 'saya',
    'sayang'                      : 'sayang',
    'sbg'                         : 'sebagai',
    'mostly'                      : 'sebagian besar',
    'sblm'                        : 'sebelum',
    'prev'                        : 'sebelumnya',
    'previous'                    : 'sebelumnya',
    'sebelumnya'                  : 'sebelumnya',
    'aslinya'                     : 'sebenarnya',
    'sbnarnya'                    : 'sebenarnya',
    'sbnrny'                      : 'sebenarnya',
    'sbnrnya'                     : 'sebenarnya',
    'sebnrnya'                    : 'sebenarnya',
    'bentar'                      : 'sebentar',
    'btar'                        : 'sebentar',
    'sbtar'                       : 'sebentar',
    'sebentar'                    : 'sebentar',
    'sebntr'                      : 'sebentar',
    'mention'                     : 'sebut',
    'asap'                        : 'secepatnya',
    'sdg'                         : 'sedang',
    'otw'                         : 'sedang dalam perjalanan',
    'simpel'                      : 'sederhana',
    'simple'                      : 'sederhana',
    'smpel'                       : 'sederhana',
    'hiks'                        : 'sedih',
    'hikss'                       : 'sedih',
    'huhu'                        : 'sedih',
    'huhuhu'                      : 'sedih',
    'huhuu'                       : 'sedih',
    'sad'                         : 'sedih',
    'sedih'                       : 'sedih',
    'dikit'                       : 'sedikit',
    'dikitt'                      : 'sedikit',
    'dkit'                        : 'sedikit',
    'sdkt'                        : 'sedikit',
    'sedikit'                     : 'sedikit',
    'harusnya'                    : 'seharusnya',
    'hrsnya'                      : 'seharusnya',
    'seharusnya'                  : 'seharusnya',
    'jadinya'                     : 'sehingga',
    'makanya'                     : 'sehingga',
    'sehingga'                    : 'sehingga',
    'sejak'                       : 'sejak',
    'since'                       : 'sejak',
    'afaik'                       : 'sejauh yang saya tahu',
    'sejenak'                     : 'sejenak',
    'amet'                        : 'sekali',
    'nian'                        : 'sekali',
    'pisan'                       : 'sekali',
    'pol'                         : 'sekali',
    'poll'                        : 'sekali',
    'puol'                        : 'sekali',
    'rn'                          : 'sekarang',
    'skarang'                     : 'sekarang',
    'skg'                         : 'sekarang',
    'skrang'                      : 'sekarang',
    'skrg'                        : 'sekarang',
    'skrng'                       : 'sekarang',
    'besides'                     : 'selain itu',
    'in addition'                 : 'selain itu',
    'selain itu'                  : 'selain itu',
    'always'                      : 'selalu',
    'selalu'                      : 'selalu',
    'forever'                     : 'selamanya',
    'selamanya'                   : 'selamanya',
    'congrats'                    : 'selamat',
    'selamat'                     : 'selamat',
    'furthermore'                 : 'selanjutnya',
    'beres'                       : 'selesai',
    'kelar'                       : 'selesai',
    'rampung'                     : 'selesai',
    'slsai'                       : 'selesai',
    'loaded'                      : 'selesai memuat',
    'solve'                       : 'selesaikan',
    'makin'                       : 'semakin',
    'smkn'                        : 'semakin',
    'tambah'                      : 'semakin',
    'makin mahal'                 : 'semakin mahal',
    'semangat'                    : 'semangat',
    'while'                       : 'sementara',
    'meanwhile'                   : 'sementara itu',
    'inshallah'                   : 'semoga',
    'insya allah'                 : 'semoga',
    'mudah2an'                    : 'semoga',
    'semoga'                      : 'semoga',
    'perfect'                     : 'sempurna',
    'sempurna'                    : 'sempurna',
    'semua'                       : 'semua',
    'semuanya'                    : 'semua',
    'smua'                        : 'semua',
    'bahagia'                     : 'senang',
    'happy'                       : 'senang',
    'senang'                      : 'senang',
    'worth'                       : 'sepadan',
    'worth it'                    : 'sepadan',
    'worthit'                     : 'sepadan',
    'cendol'                      : 'sepakat',
    'kayak'                       : 'seperti',
    'kek'                         : 'seperti',
    'kyk'                         : 'seperti',
    'sperti'                      : 'seperti',
    'sprti'                       : 'seperti',
    'spt'                         : 'seperti',
    'such as'                     : 'seperti',
    'drag'                        : 'seret',
    'often'                       : 'sering',
    'sering'                      : 'sering',
    'srg'                         : 'sering',
    'sering2'                     : 'sering-sering',
    'serius'                      : 'serius',
    'srius'                       : 'serius',
    'server'                      : 'server',
    'servers'                     : 'server',
    'occasionally'                : 'sesekali',
    'sesekali'                    : 'sesekali',
    'group session'               : 'sesi grup',
    'jam'                         : 'sesi musik',
    'sesuai selera'               : 'sesuai selera',
    'slh'                         : 'setelah',
    'stelah'                      : 'setelah',
    'stlh'                        : 'setelah',
    'abis itu'                    : 'setelah itu',
    'habis itu'                   : 'setelah itu',
    'setelahnya'                  : 'setelahnya',
    'tiap'                        : 'setiap',
    'tiap2'                       : 'setiap',
    'tiap hari'                   : 'setiap hari',
    'bet'                         : 'setuju',
    'sewaktu2'                    : 'sewaktu-waktu',
    'cast'                        : 'siarkan',
    'sih'                         : 'sih',
    'sihh'                        : 'sih',
    'save'                        : 'simpan',
    'sinkronkan'                  : 'sinkron',
    'sinkron'                     : 'sinkronisasi',
    'sync'                        : 'sinkronisasi',
    'signal'                      : 'sinyal',
    'sinyal'                      : 'sinyal',
    'sinyal bagus'                : 'sinyal baik',
    'sinyal jelek'                : 'sinyal buruk',
    'sis'                         : 'sis',
    'solution'                    : 'solusi',
    'social'                      : 'sosial',
    'soundcloud'                  : 'soundcloud',
    'spam'                        : 'spam',
    'banner'                      : 'spanduk',
    'speaker'                     : 'speaker',
    'sp'                          : 'spotify',
    'spfy'                        : 'spotify',
    'spootify'                    : 'spotify',
    'spotfy'                      : 'spotify',
    'spotif'                      : 'spotify',
    'spotifay'                    : 'spotify',
    'spotift'                     : 'spotify',
    'spoty'                       : 'spotify',
    'sptfy'                       : 'spotify',
    'sptify'                      : 'spotify',
    'spotify connect'             : 'spotify connect',
    'wrapped'                     : 'spotify wrapped',
    'stabil'                      : 'stabil',
    'stable'                      : 'stabil',
    'standar'                     : 'standar',
    'standard'                    : 'standar',
    'status'                      : 'status',
    'stereo'                      : 'stereo',
    'stream'                      : 'streaming',
    'streaming'                   : 'streaming',
    'stres'                       : 'stres',
    'stress'                      : 'stres',
    'sound'                       : 'suara',
    'suara'                       : 'suara',
    'suara pecah'                 : 'suara buruk',
    'suara jernih'                : 'suara jernih',
    'vibe'                        : 'suasana',
    'vibes'                       : 'suasana',
    'mood'                        : 'suasana hati',
    'dah'                         : 'sudah',
    'deh'                         : 'sudah',
    'sdh'                         : 'sudah',
    'sudah'                       : 'sudah',
    'udah'                        : 'sudah',
    'udahh'                       : 'sudah',
    'udh'                         : 'sudah',
    'udhaa'                       : 'sudah',
    'udhh'                        : 'sudah',
    'sudah premium'               : 'sudah berlangganan premium',
    'like'                        : 'suka',
    'likes'                       : 'suka',
    'love'                        : 'suka',
    'suka'                        : 'suka',
    'sukses'                      : 'sukses',
    'ssh'                         : 'sulit',
    'sulit'                       : 'sulit',
    'susah'                       : 'sulit',
    'susah cancel'                : 'sulit dibatalkan',
    'ribet dipake'                : 'sulit digunakan',
    'susah dipake'                : 'sulit digunakan',
    'open source'                 : 'sumber terbuka',
    'asliii'                      : 'sungguh',
    'asliiii'                     : 'sungguh',
    'beneran'                     : 'sungguh',
    'demi'                        : 'sungguh',
    'literally'                   : 'sungguh',
    'no cap'                      : 'sungguh',
    'sumpah'                      : 'sungguh',
    'sumpe'                       : 'sungguh',
    'sungguh'                     : 'sungguh',
    'seriusan'                    : 'sungguh-sungguh',
    'supaya'                      : 'supaya',
    'surround'                    : 'surround',
    'alhamdulilah'                : 'syukur',
    'alhamdulillah'               : 'syukur',
    'tablet'                      : 'tablet',
    'tadi'                        : 'tadi',
    'tdi'                         : 'tadi',
    'hashtag'                     : 'tagar',
    'tagar'                       : 'tagar',
    'tagih lagi'                  : 'tagih lagi',
    'bill'                        : 'tagihan',
    'invoice'                     : 'tagihan',
    'tagihan'                     : 'tagihan',
    'thn'                         : 'tahun',
    'tahunan'                     : 'tahunan',
    'yearly'                      : 'tahunan',
    'afraid'                      : 'takut',
    'takut'                       : 'takut',
    'fomo'                        : 'takut ketinggalan',
    'add'                         : 'tambah',
    'tmb'                         : 'tambah',
    'tmbh'                        : 'tambah',
    'display'                     : 'tampilan',
    'tampilan'                    : 'tampilan',
    'tampilan bagus'              : 'tampilan bagus',
    'tampilan jelek'              : 'tampilan buruk',
    'receipt'                     : 'tanda terima',
    'tag'                         : 'tandai',
    'chart'                       : 'tangga lagu',
    'charts'                      : 'tangga lagu',
    'top chart'                   : 'tangga lagu',
    'respon'                      : 'tanggapan',
    'response'                    : 'tanggapan',
    'screenshoot'                 : 'tangkapan layar',
    'screenshot'                  : 'tangkapan layar',
    'ss'                          : 'tangkapan layar',
    'tanpa'                       : 'tanpa',
    'tnpa'                        : 'tanpa',
    'non stop'                    : 'tanpa henti',
    'nonstop'                     : 'tanpa henti',
    'tanpa iklan'                 : 'tanpa iklan',
    'gapless'                     : 'tanpa jeda',
    'tante'                       : 'tante',
    'tapii'                       : 'tapi',
    'tp'                          : 'tapi',
    'tpi'                         : 'tapi',
    'ttapi'                       : 'tapi',
    'tekan'                       : 'tekan',
    'long press'                  : 'tekan lama',
    'tele'                        : 'telegram',
    'telegram'                    : 'telegram',
    'tg'                          : 'telegram',
    'tema'                        : 'tema',
    'theme'                       : 'tema',
    'bestie'                      : 'teman',
    'bff'                         : 'teman dekat',
    'paste'                       : 'tempel',
    'discover'                    : 'temukan',
    'find'                        : 'temukan',
    'discover weekly'             : 'temukan mingguan',
    'tntng'                       : 'tentang',
    'ttg'                         : 'tentang',
    'tb'                          : 'terabyte',
    'best'                        : 'terbaik',
    'top'                         : 'terbaik',
    'top banget'                  : 'terbaik',
    'terbaru'                     : 'terbaru',
    'update'                      : 'terbaru',
    'limited'                     : 'terbatas',
    'worset'                      : 'terburuk',
    'worst'                       : 'terburuk',
    'thd'                         : 'terhadap',
    'trhdp'                       : 'terhadap',
    'makasih'                     : 'terima kasih',
    'mks'                         : 'terima kasih',
    'mksh'                        : 'terima kasih',
    'terima kasih'                : 'terima kasih',
    'thank you'                   : 'terima kasih',
    'thanks'                      : 'terima kasih',
    'thx'                         : 'terima kasih',
    'tx'                          : 'terima kasih',
    'ty'                          : 'terima kasih',
    'affordable'                  : 'terjangkau',
    'kaget'                       : 'terkejut',
    'surprised'                   : 'terkejut',
    'kelewat'                     : 'terlalu',
    'klewat'                      : 'terlalu',
    'overly'                      : 'terlalu',
    'terlalu'                     : 'terlalu',
    'terlaluu'                    : 'terlalu',
    'overhyped'                   : 'terlalu dilebih-lebihkan',
    'overrated'                   : 'terlalu dipuji',
    'underrated'                  : 'terlalu diremehkan',
    'op'                          : 'terlalu kuat',
    'over priced'                 : 'terlalu mahal',
    'overpriced'                  : 'terlalu mahal',
    'terlalu mahal'               : 'terlalu mahal',
    'terlama'                     : 'terlama',
    'delay'                       : 'terlambat',
    'delayed'                     : 'terlambat',
    'apalagi'                     : 'terlebih',
    'terlebih'                    : 'terlebih',
    'moreover'                    : 'terlebih lagi',
    'trmasuk'                     : 'termasuk',
    'diskonek'                    : 'terputus',
    'konnek'                      : 'tersambung',
    'available'                   : 'tersedia',
    'kecharge'                    : 'tertagih',
    'tercharge'                   : 'tertagih',
    'trs'                         : 'terus',
    'trus'                        : 'terus',
    'truss'                       : 'terus',
    'keep going'                  : 'terus semangat',
    'seterusnya'                  : 'terus-menerus',
    'terus'                       : 'terus-menerus',
    'terus2'                      : 'terus-menerus',
    'especially'                  : 'terutama',
    'mainly'                      : 'terutama',
    'trutama'                     : 'terutama',
    'testimonial'                 : 'testimoni',
    'testimony'                   : 'testimoni',
    'namun'                       : 'tetapi',
    'tapi'                        : 'tetapi',
    'tetapi'                      : 'tetapi',
    'tiba2'                       : 'tiba-tiba',
    'tiba2 tagih'                 : 'tiba-tiba tagihan',
    'dak'                         : 'tidak',
    'dakk'                        : 'tidak',
    'engg'                        : 'tidak',
    'engga'                       : 'tidak',
    'enggak'                      : 'tidak',
    'g'                           : 'tidak',
    'ga'                          : 'tidak',
    'gaa'                         : 'tidak',
    'gaak'                        : 'tidak',
    'gak'                         : 'tidak',
    'gakk'                        : 'tidak',
    'ggak'                        : 'tidak',
    'gk'                          : 'tidak',
    'gkak'                        : 'tidak',
    'gkk'                         : 'tidak',
    'kagak'                       : 'tidak',
    'kagk'                        : 'tidak',
    'kgk'                         : 'tidak',
    'nah'                         : 'tidak',
    'nda'                         : 'tidak',
    'ndaa'                        : 'tidak',
    'ndak'                        : 'tidak',
    'ndk'                         : 'tidak',
    'ngak'                        : 'tidak',
    'ngga'                        : 'tidak',
    'nggaa'                       : 'tidak',
    'nggak'                       : 'tidak',
    'nggk'                        : 'tidak',
    'ngk'                         : 'tidak',
    'no'                          : 'tidak',
    'nop'                         : 'tidak',
    'nope'                        : 'tidak',
    'tak'                         : 'tidak',
    'tda'                         : 'tidak',
    'tdak'                        : 'tidak',
    'tdk'                         : 'tidak',
    'ga ada'                      : 'tidak ada',
    'gaada'                       : 'tidak ada',
    'gabut'                       : 'tidak ada kegiatan',
    'no difference'               : 'tidak ada perbedaan',
    'tidak ada respon'            : 'tidak ada tanggapan',
    'bokek'                       : 'tidak ada uang',
    'misqueen'                    : 'tidak ada uang',
    'ga ada yg'                   : 'tidak ada yang',
    'inaccurate'                  : 'tidak akurat',
    'unreliable'                  : 'tidak andal',
    'gapapa'                      : 'tidak apa-apa',
    'gppa'                        : 'tidak apa-apa',
    "doesn't work"                : 'tidak bekerja',
    'not working'                 : 'tidak bekerja',
    'ngl'                         : 'tidak berbohong',
    'useless'                     : 'tidak berguna',
    'unusual'                     : 'tidak biasa',
    "can't"                       : 'tidak bisa',
    'cant'                        : 'tidak bisa',
    'ga bisa'                     : 'tidak bisa',
    'gabisa'                      : 'tidak bisa',
    'gabsa'                       : 'tidak bisa',
    'ga bisa batal'               : 'tidak dapat dibatalkan',
    'unsupported'                 : 'tidak didukung',
    'buram'                       : 'tidak jelas',
    'ngalor ngidul'               : 'tidak jelas',
    'incompatible'                : 'tidak kompatibel',
    'deprecated'                  : 'tidak lagi didukung',
    'garing'                      : 'tidak lucu',
    'grnng'                       : 'tidak lucu',
    'emoh'                        : 'tidak mau',
    'ogah'                        : 'tidak mau',
    "won't"                       : 'tidak mau',
    'wont'                        : 'tidak mau',
    'ga ngerti selera'            : 'tidak mengerti selera',
    'abnormal'                    : 'tidak normal',
    'suboptimal'                  : 'tidak optimal',
    'receh'                       : 'tidak penting',
    'ga pernah'                   : 'tidak pernah',
    'gapernah'                    : 'tidak pernah',
    'tidak puas'                  : 'tidak puas',
    'imperfect'                   : 'tidak sempurna',
    'tidak sempurna'              : 'tidak sempurna',
    'ga sesuai selera'            : 'tidak sesuai selera',
    'labil'                       : 'tidak stabil',
    'unstable'                    : 'tidak stabil',
    'dislike'                     : 'tidak suka',
    'unlimited'                   : 'tidak terbatas',
    'unavailable'                 : 'tidak tersedia',
    'ticketing'                   : 'tiket dukungan',
    'tik tok'                     : 'tiktok',
    'tiktok'                      : 'tiktok',
    'upgrade'                     : 'tingkatkan',
    'periodt'                     : 'titik',
    'endpoint'                    : 'titik akhir',
    'token'                       : 'token',
    'toxic'                       : 'toksik',
    'tlng'                        : 'tolong',
    'tolong'                      : 'tolong',
    'button'                      : 'tombol',
    'total'                       : 'total',
    'transaction'                 : 'transaksi',
    'transfer'                    : 'transfer',
    'transparan'                  : 'transparan',
    'transparent'                 : 'transparan',
    'treble'                      : 'treble',
    'trending'                    : 'tren',
    'troll'                       : 'troll',
    'tour'                        : 'tur',
    'downgrade'                   : 'turunkan versi',
    'tutup'                       : 'tutup',
    'twitter'                     : 'twitter',
    'twt'                         : 'twitter',
    'x'                           : 'twitter',
    'change'                      : 'ubah',
    'rubah'                       : 'ubah',
    'repeat'                      : 'ulang',
    'review'                      : 'ulasan',
    'ulasan'                      : 'ulasan',
    'clickbait'                   : 'umpan klik',
    'generally'                   : 'umumnya',
    'dload'                       : 'unduh',
    'donlod'                      : 'unduh',
    'download'                    : 'unduh',
    'dwnld'                       : 'unduh',
    'dwonload'                    : 'unduh',
    'unduh'                       : 'unduh',
    'download lagu'               : 'unduh lagu',
    'upload'                      : 'unggah',
    'uplod'                       : 'unggah',
    'post'                        : 'unggahan',
    'tuk'                         : 'untuk',
    'unt'                         : 'untuk',
    'untk'                        : 'untuk',
    'utk'                         : 'untuk',
    'fyp'                         : 'untuk anda',
    'buat apa'                    : 'untuk apa',
    'bwt apa'                     : 'untuk apa',
    'napain'                      : 'untuk apa',
    'ngapain'                     : 'untuk apa',
    'fyi'                         : 'untuk diketahui',
    'usang'                       : 'usang',
    'v'                           : 'versi',
    'versi'                       : 'versi',
    'version'                     : 'versi',
    'viral'                       : 'viral',
    'vol'                         : 'volume',
    'volume'                      : 'volume',
    'voucher'                     : 'voucher',
    'wajar'                       : 'wajar',
    'wajib'                       : 'wajib',
    'wa'                          : 'whatsapp',
    'watsap'                      : 'whatsapp',
    'whatsapp'                    : 'whatsapp',
    'widget'                      : 'widget',
    'wigdet'                      : 'widget',
    'wi-fi'                       : 'wifi',
    'wifi'                        : 'wifi',
    'region'                      : 'wilayah',
    'windows'                     : 'windows',
    'anjay'                       : 'wow',
    'anjir'                       : 'wow',
    'anjrit'                      : 'wow',
    'waah'                        : 'wow',
    'wah'                         : 'wow',
    'wahh'                        : 'wow',
    'wahhhh'                      : 'wow',
    'woah'                        : 'wow',
    'wooow'                       : 'wow',
    'wow'                         : 'wow',
    'woww'                        : 'wow',
    'iya'                         : 'ya',
    'iyaa'                        : 'ya',
    'iyalah'                      : 'ya',
    'ya'                          : 'ya',
    'yaa'                         : 'ya',
    'yaah'                        : 'ya',
    'yak'                         : 'ya',
    'yasss'                       : 'ya',
    'yes'                         : 'ya',
    'yoi'                         : 'ya',
    'yoii'                        : 'ya',
    'yoiii'                       : 'ya',
    'ie'                          : 'yaitu',
    'yakin'                       : 'yakin',
    'yg'                          : 'yang',
    'yng'                         : 'yang',
    'youtu.be'                    : 'youtube',
    'youtube'                     : 'youtube',
    'yt'                          : 'youtube',
    # Entri tambahan penutup (2000+ total)
    'lemot bgt'            : 'sangat lambat',
    'eror mulu'            : 'selalu error',
    'iklan mulu'           : 'selalu ada iklan',
    'sering eror'          : 'sering error',
    'tiba2 mati'           : 'tiba-tiba mati',
    'ga mau buka'          : 'tidak mau buka',
    'ga bisa buka'         : 'tidak bisa buka',
    'susah login'          : 'sulit masuk',
    'ga bisa login'        : 'tidak bisa masuk',
    'akun hilang'          : 'akun hilang',
    'playlist hilang'      : 'playlist hilang',
    'lagu ilang'           : 'lagu hilang',
    'kuota boros'          : 'boros kuota',
    'baterai boros'        : 'boros baterai',
    'memori penuh'         : 'memori penuh',
    'storage penuh'        : 'penyimpanan penuh',
    'hp panas'             : 'ponsel panas',
}

TOTAL_ENTRIES = len(SLANG_DICT)

_NEGATION_KEYS = {k for k, v in SLANG_DICT.items() if v in ("tidak", "bukan", "jangan", "belum", "tanpa", "tidak ada", "tidak bisa", "tidak mau")}
_POSITIF_KEYS  = {k for k, v in SLANG_DICT.items() if v in ("bagus", "mantap", "keren", "oke", "luar biasa", "sempurna", "berhasil")}
_NEGATIF_KEYS  = {k for k, v in SLANG_DICT.items() if v in ("buruk", "jelek", "hancur", "rusak", "kecewa", "menyebalkan", "gagal", "lambat", "error")}

if __name__ == "__main__":
    print(f"✅ slang_dict.py loaded")
    print(f"   Total entri     : {TOTAL_ENTRIES:,}")
    print(f"   Kata negasi     : {len(_NEGATION_KEYS):,}")
    print(f"   Kata positif    : {len(_POSITIF_KEYS):,}")
    print(f"   Kata negatif    : {len(_NEGATIF_KEYS):,}")
    print()
    print("   Contoh lookup:")
    for sample in ["gak", "bgt", "lemot", "mantep", "jelek", "download", "spoty", "ngelag", "ga bisa"]:
        val = SLANG_DICT.get(sample, "[tidak ada]")
        print(f"     {sample:20s} → {val}")
