import { NAVIGATION_ITEMS } from "@/constants/navigation";
import type {
  AhpCriterion,
  AhpResult,
  AspectSummary,
  EvaluationSummary,
  FuzzyAhpResult,
  NavigationItem,
  ReportSummary,
  Review,
  SentimentSummary,
} from "@/types";

// Synthetic UI-only data. Do not treat these values as final method output.
export const mockReviews = [
  {
    id: "rev-001",
    source: "spotify_play_store",
    userName: "Alya",
    rating: 5,
    text: "Spotify keeps my commute easy. The recommendations are usually accurate and the playlists update at the right time.",
    cleanedText:
      "spotify keeps commute easy recommendations usually accurate playlists update right time",
    language: "en",
    reviewDate: "2026-04-12",
    appVersion: "9.0.24",
    thumbsUpCount: 18,
    sentimentLabel: "positive",
    sentimentConfidence: 0.94,
    aspectLabels: ["recommendation", "playlist_library"],
    isProcessed: true,
  },
  {
    id: "rev-002",
    source: "spotify_play_store",
    userName: "Bima",
    rating: 2,
    text: "Too many ads play between songs. Sometimes I hear two ads before one short track.",
    cleanedText: "too many ads play between songs sometimes hear two ads before one short track",
    language: "en",
    reviewDate: "2026-04-13",
    appVersion: "9.0.24",
    thumbsUpCount: 41,
    sentimentLabel: "negative",
    sentimentConfidence: 0.91,
    aspectLabels: ["ads"],
    isProcessed: true,
  },
  {
    id: "rev-003",
    source: "spotify_play_store",
    userName: "Citra",
    rating: 3,
    text: "The app works fine for daily listening, but the lyrics are not available for several local songs.",
    cleanedText: "app works fine daily listening lyrics not available several local songs",
    language: "en",
    reviewDate: "2026-04-14",
    appVersion: "9.0.25",
    thumbsUpCount: 9,
    sentimentLabel: "neutral",
    sentimentConfidence: 0.78,
    aspectLabels: ["lyrics"],
    isProcessed: true,
  },
  {
    id: "rev-004",
    source: "spotify_play_store",
    userName: "Dimas",
    rating: 1,
    text: "Songs stop randomly after the recent update and the app becomes slow when I open my library.",
    cleanedText: "songs stop randomly recent update app becomes slow open library",
    language: "en",
    reviewDate: "2026-04-15",
    appVersion: "9.0.25",
    thumbsUpCount: 57,
    sentimentLabel: "negative",
    sentimentConfidence: 0.96,
    aspectLabels: ["app_performance", "playlist_library"],
    isProcessed: true,
  },
  {
    id: "rev-005",
    source: "spotify_play_store",
    userName: "Eka",
    rating: 4,
    text: "Premium is worth it for offline listening. Downloaded playlists work well during travel.",
    cleanedText: "premium worth offline listening downloaded playlists work well travel",
    language: "en",
    reviewDate: "2026-04-16",
    appVersion: "9.0.25",
    thumbsUpCount: 23,
    sentimentLabel: "positive",
    sentimentConfidence: 0.9,
    aspectLabels: ["subscription", "offline_download"],
    isProcessed: true,
  },
  {
    id: "rev-006",
    source: "spotify_play_store",
    userName: "Fajar",
    rating: 2,
    text: "Offline songs disappear even though I still have storage. I need to download the same playlist again.",
    cleanedText: "offline songs disappear still have storage need download same playlist again",
    language: "en",
    reviewDate: "2026-04-18",
    appVersion: "9.0.26",
    thumbsUpCount: 35,
    sentimentLabel: "negative",
    sentimentConfidence: 0.89,
    aspectLabels: ["offline_download", "playlist_library"],
    isProcessed: true,
  },
  {
    id: "rev-007",
    source: "spotify_play_store",
    userName: "Gita",
    rating: 3,
    text: "Search results are acceptable, but podcast recommendations are not relevant for me.",
    cleanedText: "search results acceptable podcast recommendations not relevant",
    language: "en",
    reviewDate: "2026-04-19",
    appVersion: "9.0.26",
    thumbsUpCount: 7,
    sentimentLabel: "neutral",
    sentimentConfidence: 0.74,
    aspectLabels: ["recommendation"],
    isProcessed: true,
  },
  {
    id: "rev-008",
    source: "spotify_play_store",
    userName: "Hadi",
    rating: 1,
    text: "I was charged for Premium but my account still shows free. Support takes too long to respond.",
    cleanedText: "charged premium account still shows free support takes too long respond",
    language: "en",
    reviewDate: "2026-04-20",
    appVersion: "9.0.26",
    thumbsUpCount: 64,
    sentimentLabel: "negative",
    sentimentConfidence: 0.93,
    aspectLabels: ["subscription", "account_login"],
    isProcessed: true,
  },
  {
    id: "rev-009",
    source: "spotify_play_store",
    userName: "Intan",
    rating: 5,
    text: "The audio quality is stable and the daily mix helps me discover new artists quickly.",
    cleanedText: "audio quality stable daily mix helps discover new artists quickly",
    language: "en",
    reviewDate: "2026-04-22",
    appVersion: "9.0.27",
    thumbsUpCount: 16,
    sentimentLabel: "positive",
    sentimentConfidence: 0.92,
    aspectLabels: ["audio_quality", "recommendation"],
    isProcessed: true,
  },
  {
    id: "rev-010",
    source: "spotify_play_store",
    userName: "Joko",
    rating: 2,
    text: "The family plan price increased and the app still freezes when switching playlists.",
    cleanedText: "family plan price increased app still freezes switching playlists",
    language: "en",
    reviewDate: "2026-04-23",
    appVersion: "9.0.27",
    thumbsUpCount: 29,
    sentimentLabel: "negative",
    sentimentConfidence: 0.88,
    aspectLabels: ["pricing", "app_performance"],
    isProcessed: true,
  },
] satisfies Review[];

export const mockSentimentSummary = {
  totalReviews: 10,
  counts: {
    positive: 3,
    neutral: 2,
    negative: 5,
  },
  percentages: {
    positive: 30,
    neutral: 20,
    negative: 50,
  },
  dominantLabel: "negative",
  averageConfidence: 0.885,
  modelName: "IndoBERT Sentiment",
  modelVersion: "mock-ui-contract-1",
  generatedAt: "2026-05-30T09:00:00+07:00",
} satisfies SentimentSummary;

export const mockAspectSummary = {
  totalClassified: 10,
  counts: {
    audio_quality: 1,
    recommendation: 3,
    ads: 1,
    subscription: 2,
    app_performance: 2,
    playlist_library: 3,
    lyrics: 1,
    offline_download: 2,
    account_login: 1,
    pricing: 1,
  },
  negativeCounts: {
    audio_quality: 0,
    recommendation: 0,
    ads: 1,
    subscription: 1,
    app_performance: 2,
    playlist_library: 2,
    lyrics: 0,
    offline_download: 1,
    account_login: 1,
    pricing: 1,
  },
  topAspect: "playlist_library",
  topNegativeAspect: "app_performance",
  multiAspectReviewCount: 6,
  modelName: "SVM Aspect Classifier",
  modelVersion: "mock-ui-contract-1",
  generatedAt: "2026-05-30T09:05:00+07:00",
} satisfies AspectSummary;

export const mockAhpCriteria = [
  {
    id: "crit-app-performance",
    label: "App Performance Stability",
    description: "Prioritize crash, lag, and playback interruption complaints.",
    source: "aspect_classification",
    sourceAspect: "app_performance",
    evidenceCount: 2,
    negativeReviewCount: 2,
    isActive: true,
  },
  {
    id: "crit-ads",
    label: "Ad Interruption",
    description: "Prioritize ad frequency and interruption issues in free listening.",
    source: "aspect_classification",
    sourceAspect: "ads",
    evidenceCount: 1,
    negativeReviewCount: 1,
    isActive: true,
  },
  {
    id: "crit-offline-download",
    label: "Offline Download Reliability",
    description: "Prioritize downloaded playlist availability and offline playback.",
    source: "aspect_classification",
    sourceAspect: "offline_download",
    evidenceCount: 2,
    negativeReviewCount: 1,
    isActive: true,
  },
  {
    id: "crit-subscription",
    label: "Subscription and Account Billing",
    description: "Prioritize Premium activation, renewal, and account billing issues.",
    source: "aspect_classification",
    sourceAspect: "subscription",
    evidenceCount: 2,
    negativeReviewCount: 1,
    isActive: true,
  },
  {
    id: "crit-pricing",
    label: "Pricing Sensitivity",
    description: "Prioritize price increase and perceived value complaints.",
    source: "aspect_classification",
    sourceAspect: "pricing",
    evidenceCount: 1,
    negativeReviewCount: 1,
    isActive: true,
  },
] satisfies AhpCriterion[];

export const mockAhpResult = {
  id: "ahp-result-demo-001",
  criteria: mockAhpCriteria,
  pairwiseComparisons: [
    {
      id: "pc-001",
      criterionAId: "crit-app-performance",
      criterionBId: "crit-ads",
      value: 3,
      reciprocalValue: 0.333,
      scaleLabel: "Moderately more important",
    },
    {
      id: "pc-002",
      criterionAId: "crit-app-performance",
      criterionBId: "crit-offline-download",
      value: 2,
      reciprocalValue: 0.5,
      scaleLabel: "Slightly more important",
    },
    {
      id: "pc-003",
      criterionAId: "crit-app-performance",
      criterionBId: "crit-subscription",
      value: 2,
      reciprocalValue: 0.5,
      scaleLabel: "Slightly more important",
    },
    {
      id: "pc-004",
      criterionAId: "crit-app-performance",
      criterionBId: "crit-pricing",
      value: 4,
      reciprocalValue: 0.25,
      scaleLabel: "Between moderate and strong",
    },
    {
      id: "pc-005",
      criterionAId: "crit-ads",
      criterionBId: "crit-offline-download",
      value: 0.5,
      reciprocalValue: 2,
      scaleLabel: "Slightly less important",
    },
    {
      id: "pc-006",
      criterionAId: "crit-ads",
      criterionBId: "crit-subscription",
      value: 1,
      reciprocalValue: 1,
      scaleLabel: "Equal importance",
    },
    {
      id: "pc-007",
      criterionAId: "crit-ads",
      criterionBId: "crit-pricing",
      value: 2,
      reciprocalValue: 0.5,
      scaleLabel: "Slightly more important",
    },
    {
      id: "pc-008",
      criterionAId: "crit-offline-download",
      criterionBId: "crit-subscription",
      value: 1,
      reciprocalValue: 1,
      scaleLabel: "Equal importance",
    },
    {
      id: "pc-009",
      criterionAId: "crit-offline-download",
      criterionBId: "crit-pricing",
      value: 2,
      reciprocalValue: 0.5,
      scaleLabel: "Slightly more important",
    },
    {
      id: "pc-010",
      criterionAId: "crit-subscription",
      criterionBId: "crit-pricing",
      value: 2,
      reciprocalValue: 0.5,
      scaleLabel: "Slightly more important",
    },
  ],
  ranking: [
    {
      criterionId: "crit-app-performance",
      label: "App Performance Stability",
      weight: 0.34,
      rank: 1,
      interpretation: "Most urgent because reliability issues block listening sessions.",
      evidenceCount: 2,
    },
    {
      criterionId: "crit-offline-download",
      label: "Offline Download Reliability",
      weight: 0.22,
      rank: 2,
      interpretation: "High impact for Premium users and travel scenarios.",
      evidenceCount: 2,
    },
    {
      criterionId: "crit-subscription",
      label: "Subscription and Account Billing",
      weight: 0.19,
      rank: 3,
      interpretation: "Important because billing issues directly affect trust.",
      evidenceCount: 2,
    },
    {
      criterionId: "crit-ads",
      label: "Ad Interruption",
      weight: 0.15,
      rank: 4,
      interpretation: "Relevant for free users, but less severe than playback failures.",
      evidenceCount: 1,
    },
    {
      criterionId: "crit-pricing",
      label: "Pricing Sensitivity",
      weight: 0.1,
      rank: 5,
      interpretation: "Needs monitoring, but current evidence is narrower.",
      evidenceCount: 1,
    },
  ],
  consistencyRatio: 0.07,
  consistencyStatus: "consistent",
  generatedAt: "2026-05-30T09:10:00+07:00",
  methodVersion: "mock-ahp-contract-1",
  methodNote:
    "Mock ranking for UI development only. Frontend does not calculate AHP weights.",
} satisfies AhpResult;

export const mockFuzzyAhpResult = {
  id: "fuzzy-ahp-result-demo-001",
  criteria: mockAhpCriteria,
  scaleOptions: [
    {
      id: "fuzzy-equal",
      label: "Equal importance",
      value: { lower: 1, middle: 1, upper: 1 },
    },
    {
      id: "fuzzy-slight",
      label: "Slightly more important",
      value: { lower: 1, middle: 2, upper: 3 },
    },
    {
      id: "fuzzy-moderate",
      label: "Moderately more important",
      value: { lower: 2, middle: 3, upper: 4 },
    },
    {
      id: "fuzzy-strong",
      label: "Strongly more important",
      value: { lower: 4, middle: 5, upper: 6 },
    },
  ],
  ranking: [
    {
      criterionId: "crit-app-performance",
      label: "App Performance Stability",
      fuzzyWeight: { lower: 0.29, middle: 0.35, upper: 0.41 },
      normalizedWeight: 0.35,
      rank: 1,
      interpretation: "Prototype fuzzy ranking also places reliability as top priority.",
    },
    {
      criterionId: "crit-offline-download",
      label: "Offline Download Reliability",
      fuzzyWeight: { lower: 0.18, middle: 0.22, upper: 0.27 },
      normalizedWeight: 0.22,
      rank: 2,
      interpretation: "Offline reliability remains a high-priority Premium experience issue.",
    },
    {
      criterionId: "crit-subscription",
      label: "Subscription and Account Billing",
      fuzzyWeight: { lower: 0.15, middle: 0.19, upper: 0.24 },
      normalizedWeight: 0.19,
      rank: 3,
      interpretation: "Billing and account trust remain important.",
    },
    {
      criterionId: "crit-ads",
      label: "Ad Interruption",
      fuzzyWeight: { lower: 0.11, middle: 0.14, upper: 0.18 },
      normalizedWeight: 0.14,
      rank: 4,
      interpretation: "Ad interruption is visible but not the top prototype priority.",
    },
    {
      criterionId: "crit-pricing",
      label: "Pricing Sensitivity",
      fuzzyWeight: { lower: 0.07, middle: 0.1, upper: 0.14 },
      normalizedWeight: 0.1,
      rank: 5,
      interpretation: "Pricing is tracked as a lower-evidence issue in this mock set.",
    },
  ],
  status: "prototype",
  generatedAt: "2026-05-30T09:12:00+07:00",
  methodVersion: "mock-fuzzy-ahp-contract-1",
  methodNote:
    "Prototype mock output only. Final Fuzzy AHP formula and output shape remain backend/methodology concerns.",
} satisfies FuzzyAhpResult;

export const mockModelEvaluation = {
  generatedAt: "2026-05-30T09:15:00+07:00",
  models: [
    {
      task: "sentiment",
      modelName: "IndoBERT Sentiment",
      modelVersion: "mock-ui-contract-1",
      sampleCount: 600,
      metrics: [
        {
          id: "metric-sentiment-accuracy",
          task: "sentiment",
          label: "Accuracy",
          value: 0.88,
          format: "percentage",
          description: "Overall sentiment classification accuracy on validation data.",
        },
        {
          id: "metric-sentiment-macro-f1",
          task: "sentiment",
          label: "Macro F1",
          value: 0.84,
          format: "percentage",
          description: "Average F1 across positive, neutral, and negative labels.",
        },
        {
          id: "metric-sentiment-neutral-recall",
          task: "sentiment",
          label: "Neutral Recall",
          value: 0.78,
          format: "percentage",
          description: "Recall for neutral reviews, tracked because this class is often weaker.",
        },
      ],
      confusionMatrix: {
        id: "cm-sentiment",
        task: "sentiment",
        labels: ["positive", "neutral", "negative"],
        rows: [
          {
            actualLabel: "positive",
            predictedCounts: { positive: 174, neutral: 17, negative: 9 },
            support: 200,
          },
          {
            actualLabel: "neutral",
            predictedCounts: { positive: 22, neutral: 156, negative: 22 },
            support: 200,
          },
          {
            actualLabel: "negative",
            predictedCounts: { positive: 8, neutral: 14, negative: 178 },
            support: 200,
          },
        ],
      },
      notes: [
        "Neutral recall is tracked as a watch item for thesis evaluation.",
        "Mock values are synthetic and only support UI layout development.",
      ],
    },
    {
      task: "aspect",
      modelName: "SVM Aspect Classifier",
      modelVersion: "mock-ui-contract-1",
      sampleCount: 420,
      metrics: [
        {
          id: "metric-aspect-accuracy",
          task: "aspect",
          label: "Accuracy",
          value: 0.82,
          format: "percentage",
          description: "Overall aspect classification accuracy on validation data.",
        },
        {
          id: "metric-aspect-macro-f1",
          task: "aspect",
          label: "Macro F1",
          value: 0.79,
          format: "percentage",
          description: "Average F1 across Spotify review aspect labels.",
        },
      ],
      confusionMatrix: {
        id: "cm-aspect",
        task: "aspect",
        labels: ["ads", "app_performance", "offline_download", "subscription"],
        rows: [
          {
            actualLabel: "ads",
            predictedCounts: { ads: 80, app_performance: 6, offline_download: 4, subscription: 5 },
            support: 95,
          },
          {
            actualLabel: "app_performance",
            predictedCounts: { ads: 9, app_performance: 92, offline_download: 8, subscription: 6 },
            support: 115,
          },
          {
            actualLabel: "offline_download",
            predictedCounts: { ads: 5, app_performance: 10, offline_download: 74, subscription: 6 },
            support: 95,
          },
          {
            actualLabel: "subscription",
            predictedCounts: { ads: 6, app_performance: 9, offline_download: 8, subscription: 92 },
            support: 115,
          },
        ],
      },
      notes: [
        "Aspect labels remain reusable for future API response mapping.",
        "Confusion matrix labels can be expanded when the final dataset has more classes.",
      ],
    },
  ],
  overallNotes: [
    "Evaluation values are synthetic placeholders for frontend UI development.",
    "Final values must come from validated model artifacts before thesis reporting.",
  ],
} satisfies EvaluationSummary;

export const mockReportSummary = {
  id: "report-demo-001",
  title: "SentiRank Spotify Review Insight Summary",
  generatedAt: "2026-05-30T09:20:00+07:00",
  dataset: {
    totalReviews: 10,
    source: "Synthetic Spotify review sample for UI development",
    dateRange: {
      start: "2026-04-12",
      end: "2026-04-23",
    },
  },
  sentiment: {
    dominantLabel: "negative",
    negativeRate: 50,
    positiveRate: 30,
    neutralRate: 20,
  },
  aspect: {
    topNegativeAspect: "app_performance",
    topNegativeAspectCount: 2,
  },
  prioritization: {
    recommendedAspect: "app_performance",
    ahpWeight: 0.34,
    fuzzyAhpWeight: 0.35,
    interpretation:
      "App performance should be handled first because playback reliability directly affects the core listening experience.",
  },
  evaluation: {
    sentimentMacroF1: 0.84,
    aspectMacroF1: 0.79,
  },
  highlights: [
    "Negative reviews dominate this synthetic demo sample.",
    "App performance appears as the top negative aspect and top priority.",
    "AHP and Fuzzy AHP mock rankings produce the same first recommendation.",
  ],
  recommendations: [
    "Use model outputs to focus improvement discussion on reliability and playback stability.",
    "Keep AHP/Fuzzy AHP results clearly labeled as method outputs when final backend data is connected.",
  ],
} satisfies ReportSummary;

export const mockNavigationItems = NAVIGATION_ITEMS satisfies readonly NavigationItem[];
